/*
 
 # 1044. Longest Duplicate Substring

 # Given a string S, consider all duplicated substrings: (contiguous) substrings of S that occur 2 or more times.
 # (The occurrences may overlap.)

 # Return any duplicated substring that has the longest possible length.
 # (If S does not have a duplicated substring, the answer is "".)


 # Example 1:

 # Input: "banana"
 # Output: "ana"

 # Example 2:

 # Input: "abcd"
 # Output: ""


 # Note:

 # 2 <= S.length <= 10^5
 # S consists of lowercase English letters.
 
 
 */
#include <string>
using std::string;

#include <vector>
using std::vector;

#include <unordered_set>
using std::unordered_set;

#include <math.h>

#include <unordered_map>
using std::unordered_map;

class longestDupSubstring {
    
public:
    
    string doit_hashtable(string S) {
        
        int N = S.length();
        vector<short> nums;
        int base = 26;
        int64_t mod = pow(2, 32);
        
        auto search = [N](int L, int base, int64_t mod, vector<short>& nums){
        
            long int hash = 0;
            for (int i = 0; i < L; i++)
                hash = (hash * base + nums[i]) % mod;
            
            unordered_set<int> seen;
            seen.insert(hash);
            int al = int64_t(pow(base, L)) % mod;
            
            for (int s = 1; s < N - L + 1; s++) {
                hash = (hash * base - nums[s-1] * al + nums[s+L-1]) % mod;
                if (seen.count(hash) != 0) {
                    return s;
                }
                seen.insert(hash);
            }
            return -1;
        };
        
        for (auto c : S) {
            nums.push_back(c - 'a');
        }
        
        int left = 1, right = nums.size();
        
        while (left <= right) {
            int mid = (left + right) / 2;
            
            if (search(mid, base, mod, nums) != -1) {
                left = mid + 1;
            } else {
                right = mid - 1;
            }
        }
        
        int s = search(left - 1, base, mod, nums);
        return S.substr(s, left - 1);
    }

    
    string doit_rollinghash_binary_search(string S) 
    {
        int left = 1, right = S.size()-1;
        unordered_map<int,int> len2start;

        auto found = [&](string&S, int len) {

            unordered_set<long long>Set;
            long long base = 26;
            long long mod = (1l<<32);
            long long hash = 0;

            long long pow_base_len = 1;
            for (int i=0; i<len; i++)        
                pow_base_len = (pow_base_len * base) % mod;                    
                
            for (int i = 0; i < S.size(); i++)
            {
                hash = (hash * base + (S[i]-'a')) % mod;
                if (i>=len)            
                    hash = (hash - pow_base_len*(S[i-len]-'a') % mod + mod) % mod;

                if (i>=len-1)
                {                
                    if (Set.find(hash)!=Set.end())
                    {
                        len2start[len] = i-len+1;
                        return true;
                    }                
                    Set.insert(hash);
                }          
            }
            return false;
        };

        while (left < right) {
            int mid = right - (right-left)/2;
            if (found(S,mid))
                left = mid;
            else
                right = mid - 1;
        }

        if (found(S, left)) // Maybe doesn't find target, so call found again.
            return S.substr(len2start[left],left);
        else
            return "";        
    }

    
};

void test_1044_longest_duplicate_substring() {
 
    auto res1 = longestDupSubstring().doit("banana");
    
    auto res2 = longestDupSubstring().doit("abcd");
    
    auto res3 = longestDupSubstring().doit("moplvidmaagmsiyyrkchbyhivlqwqsjcgtumqscmxrxrvwsnjjvygrelcbjgbpounhuyealllginkitfaiviraqcycjmskrozcdqylbuejrgfnquercvghppljmojfvylcxakyjxnampmakyjbqgwbyokaybcuklkaqzawageypfqhhasetugatdaxpvtevrigynxbqodiyioapgxqkndujeranxgebnpgsukybyowbxhgpkwjfdywfkpufcxzzqiuglkakibbkobonunnzwbjktykebfcbobxdflnyzngheatpcvnhdwkkhnlwnjdnrmjaevqopvinnzgacjkbhvsdsvuuwwhwesgtdzuctshytyfugdqswvxisyxcxoihfgzxnidnfadphwumtgdfmhjkaryjxvfquucltmuoosamjwqqzeleaiplwcbbxjxxvgsnonoivbnmiwbnijkzgoenohqncjqnckxbhpvreasdyvffrolobxzrmrbvwkpdbfvbwwyibydhndmpvqyfmqjwosclwxhgxmwjiksjvsnwupraojuatksjfqkvvfroqxsraskbdbgtppjrnzpfzabmcczlwynwomebvrihxugvjmtrkzdwuafozjcfqacenabmmxzcueyqwvbtslhjeiopgbrbvfbnpmvlnyexopoahgmwplwxnxqzhucdieyvbgtkfmdeocamzenecqlbhqmdfrvpsqyxvkkyfrbyolzvcpcbkdprttijkzcrgciidavsmrczbollxbkytqjwbiupvsorvkorfriajdtsowenhpmdtvamkoqacwwlkqfdzorjtepwlemunyrghwlvjgaxbzawmikfhtaniwviqiaeinbsqidetfsdbgsydkxgwoqyztaqmyeefaihmgrbxzyheoegawthcsyyrpyvnhysynoaikwtvmwathsomddhltxpeuxettpbeftmmyrqclnzwljlpxazrzzdosemwmthcvgwtxtinffopqxbufjwsvhqamxpydcnpekqhsovvqugqhbgweaiheeicmkdtxltkalexbeftuxvwnxmqqjeyourvbdfikqnzdipmmmiltjapovlhkpunxljeutwhenrxyfeufmzipqvergdkwptkilwzdxlydxbjoxjzxwcfmznfqgoaemrrxuwpfkftwejubxkgjlizljoynvidqwxnvhngqakmmehtvykbjwrrrjvwnrteeoxmtygiiygynedvfzwkvmffghuduspyyrnftyvsvjstfohwwyxhmlfmwguxxzgwdzwlnnltpjvnzswhmbzgdwzhvbgkiddhirgljbflgvyksxgnsvztcywpvutqryzdeerlildbzmtsgnebvsjetdnfgikrbsktbrdamfccvcptfaaklmcaqmglneebpdxkvcwwpndrjqnpqgbgihsfeotgggkdbvcdwfjanvafvxsvvhzyncwlmqqsmledzfnxxfyvcmhtjreykqlrfiqlsqzraqgtmocijejneeezqxbtomkwugapwesrinfiaxwxradnuvbyssqkznwwpsbgatlsxfhpcidfgzrc");
    
    auto res4 = longestDupSubstring().doit("bwvzoubsovtdpokbjgubpkzsdmxpdxwrkjzjbhcuvppjowoaapfpaqmgpkflwookqdujdfqsifdbkmwqfumwhotpdmevmshumjcdquspnihgceaedgxjgrtjdxqacznaluiiwrivaulamzyecdpyfyxmiavwkqvbybabmshszoslhxzhmaqtvhbnznnxuyctrbywifcuguutkdxchpyxurmskwbygnbtatoxwesmtzchjlrnqsjxanoemmzsqcraykiszrieoaqcwcwlyorrcvlamxztujsglqcwjmqvcmmuwwjgkdfhfxfahlefserldejymbhgdddlwjllantqxeivdbrsbjdcsgrcngejbfvwdjbaffvarzdkizozlszqvzsyszqklvinaypeqyppcyafzqkdlreddrmbxwiikymgcqaghptuvbgkoebirotkfdxcfxeykqvdqlbmnbpgumksbsdwdbyqfdwdqpfustxqorwpxyatjuiocqjytiqzymfkyagtxqypmwnppqwpoltglrpalpextaglktgzauzwxnzgwqfvxitoqkiqcacpcetzscypoumazhyjtqhflnihtmboxmqqqvahqsukxebqnyxpyoiczdjikslukjvgeejnirpijjkhdjrfkjrvvqlrdpzwfyredgxljfjmbtrkpdydmpqqvywtqmdcyrtapmqwhkaocdzkamlbunnfhfcfpoechlqripwsmskcprihcnptbqyqxdnhewuehycuaxbzxbftjaqsfqtvmfvisepjnrzqibkbwtncipwcejllhlqxylwzmquwqgbizbumshhoxwvexjxgiexmjfsrfnplybfdouqggsntludnaznsbnloorlwkhicbzrfvcqohmlzojfdsyzjniyoinfszmaelknerpwgmctnkjjnixlmxjdvpxjjbonmfxrxgpxrculamkmwwnrxgsjlwdohonruecrtuknjjjgsmcctqdfsttcikawjaowskacuretxcdqnkapiiiwezklfnbayedclkkdwdqqsmxqupcphgdmaldcnidadhpvyvbsprbrqpifrpdsjgwvoxumxeuybmcwbmuyacvrfqfkuszjpwyjwbmrhbbvdmhwrowsqahmeexucshsvknchkzljwoztqgrthoeldityevjljhavuqcxgwzcoyvsjoxvmlrxtytlomorbfkskzkfzhbhqjumnwzbfaalogdwztbeirzxitgbmfcwkkgfwapubspmhuygtfhsxjcoklybqoultxvmtactpqqsgewzzguxndxouiacalpopiovashsfcnftuaxaafwjhruheabclgjjyxpaiyuqjybpkdzkyrfnxfwcvdedcfqiseljtebxzcjqmqkhyiurdiybznjnkzaqthrpanhflnunqucliwsdttzbkmndrckzucllnjosvryowfkielbdziuqhiilbbsfbllxjyodgurluibsfjxqoupbxfpxkjscslirbszjmhklgevhdrqykonnnekacqtcworjpgxuraikciaburspaldpihnyafojwmclckulomsyyzxonthymcffhlxjfzonzxpwkpihianrywxejbghxrvsadkhljtubrenaemecmmvesijfqpthrkhiqhdrkvxlrkciaklncrnxzdhcsuaesjmbjlupwvwjfelxipbaligpeojbrvosyimousrqaenebgeleuuybixbwirltnctluazywoqcefcrejgtlfruyiotcbmubuqxbdthtakywfopbvkysddivfaaqaylpoadazdskcuhklvuqmbguwtlaawymbkveoszsysramyowewkheriglqwqejursmaiyhmnrlxryolizwsywgaizflzghtammlntphjmvlvyujgfsjlscpjhavxbeutapfieswtpldeeuxetbqphkqibwdzfeqbjxaryeogyirhleulfeeprmshdmiikfhuqxxpxdryenhdzgxojixhcjswllduemothoxzzpbiapvinihgucazbvggihobmscpijwcavhqxlcenuqjjjpehpreyccucfiecnyflxojxdskncvvdpwzrlwkfhhvgcdeevtflgwypgvvuzlntncpqiczyzxoxsfabybcxlarysptirnzpbzfzlagchruxjfzibrwfyxtyydathyctagcnokpwqfiowsdjvfrnzogemfchwitmoqsoezqdkwefjufdnvnhogqzzcqngkgaiwoqofwjtdygktqvmzcwwmzemvxlgryjjzoyguwjuczziosldbwwygftujlpzanbszeaakidazfpdtbnrowhnlqgyvssziolsfedivgsqvamcliuqeemeorxlrzyofbiozdpuobjwuxglvuuvxebvsnxomfziirlvhuqxjwunehjcqjnmlliqkywwmguloxmapflwhoddpqzduyfkizkneooifsndynggljsfbjcfzahmkambrojzdbatgtimxiisguvdpftjcwmjxbqyaltbgvfefyqwnminsuqraztojpshmlrqtrbpyiekbanjjndnfkhlyihbmxvwyrfomlpcsbrkrptkfyapjctyoruxdwrzjgcrfsxytlripxckhabdqnxwyiidegjwsqvqckjhlmlvdhfnlclizhdpsvmsrkbrzahcuvonpizhyrwilmbmwexzzohvlhzfcqcwhfgamikhkhfrwmymvxrmbypdurouthrlzubtclfltanroeegkfjqqrjxwgyzymcoopcubqvghnckoccjdicffridjupfylgseipqgbshoesjjcjhpyodpituvipopeizgwortgqvotiyfzfnkixcsbuywrxowetievuudmwtnxcbbxpotkcuqmxczzldimrdulntjsieciuebztdtfftligeybplqculadfvnqqxdbrnjqgptjlhqrutfvsiencukxpioekrszfgryxsbcaqaabbsvskhpivnedwejrnooejfvfmozywtkntdcpphrwnnqdvnakujmrqymxgetisbvllvcszyaojatpmogehyfaecerykkratgouegtfsetpywknkhzgzmpdwkjmvimnpjtloqumcntnhqxnbzycwrhkxwaxhweefmrlnemyoeygyxrbwpkrtsbzqkapxkobfoytbhvemmqhnjipwsjenrcegvbbkwjjuckixszmptqbydsigpatqsbybivryjxfcbmjprfleoxhfpdpzwujtbbzunbuvqaxwlrfxsnfhsereyewipnradhqocwyvllxfsyvfmdxmntdjbkjhewufyackxviawolgyevjfitgtvaitkexckrxcwvhqyhfqkjrxnmsgavnxdwqxzdfykfkohprhmiuzlrhnkgcprtnixgjosfgdkbecvwhjeghxbnshmmzqfrbeaepzujjopmfwwgwdkguunugjtwronvdwthlzipilehrnfdxlflyspxdounyhjdkbmdgprqqebpgszrpjwpzsfapdtgyunjgzgvernvkvxfwnxahwbawjrivczeomcjoecuckeglrmgygpqmrpraujjbcrtgdqvhtszwulmwdzxswtwmdpmcuyqirrfujrcrbjpxnklyehmsifbfgpprdtptrjtaauoxguntymzlqroucijjaqtbdipxcrikfbiavjkpapsgfuvgojbdklidflwdqpyddgylyfpkxjpopsnlxpfhngjhpsifbdfpgmtluxrevxczumrddonelqdtzrtyswsokhjjybjlfkoxeeluioxrjkjbkfnzoesywvdegskgbnnxenlwjxibbzfuygcvdrijueiegvapxhrhsqsdvdstbjjmpuotzceluhiqxxhowtfafltqipugbbubtixdgutxbbfpaqqrpurxytjbomgsncnvsibaedbtmvnvhtfsiviotjzikmkahwckcjgxdovdhjynlhhplbkklowfyfwlaobxazpdeyjxaikvcujspctbsaboohilrgrpmyuvwmkrutzlrjjmsczxdwestatrrthgkewhfqfwfsigntrpkxnfrrlxszvpwvodornyrjpeepsdaoqbqcfoptrjbcnjqyepnumdwwqzrohiipounayuklksidvysyoaquhnsnafwxusqhnqhqdsguuuopbnfugprvblrpnykxegzqqmcuehhsmbxuymbbvddfjmqplxqndjtvkwpockfyigspcryulkqunugsxqsvmqxfruegmqbdhrpqyofhjuichixisrqovmgvsaitcwvbouslnqnwbxuyldltrsbdasafhjzbcwsholeetygedllizzxmjzfrnsjkpphgulpkiaizbgprspjfvwoivvfqafqhfrtpmccrjaqdqqnrrjidjvpmbovopcqkeykqrsdykrenmrmgrzfycwkrmajzertyobgrkabhqrhrvtswtlinrwjrafiwlggeibhtlwpaesbdvqkvrwlkmyxdfdzocqagjssirvhgvqqxuzzzborhilzmcuwmdbbxyfhoveudokxrtgfkauvukprmtmtoyprgnghqvujfhanwzogstrrvixbkwadnbmddidciqeshyfmmevtttyzldbyrkmcwcvghywscejheyaegfihroufxjzpfgwynwqsrcuqufjxftyqozyvkjvyjaxutnheqzwqftvidgbfnmirwqrxnmwfnqmqqqvflyekoakzfbcdgesabnaxlgnetkmqgobnyplpndyaahqfghpeginvovqdnknoimrwyttackovtkpyyuzmufutvkjpcpmuhmzxnutduwjcoycjolneqinpqmltgtwfxddaksdmggdtdxhdsvbclxiuowmbhdrmxrexzxbmzvxhpnjssdwginukazqbwddoaryxsgswgphlsjtylqnkqcfwrcprhashjjgfqadgbvdlmhqeutwsuuohzmpkbqhlmwbnfgurkryfeiezahdccpujbatzozvxwwshfhkpmvgdyqcyfduruseuylxgwjsxoaneqzaxmacwixtnsjbfqhvpqscbdxeuuirwqudavgnfsmiuiedqbshrwirrpfodjhicsmikoztytnsgncsrchrzthxnvowckygpbyybzqaqmzncyictygqpuchnknpghotmnlbioojhiboigybydgcfxpzpqsmuvorcojgmaeglnzqgndyytzowmtkntcfahrseijgnzjftsmezyzzbawybsyaspibinurjnnoqfkmlkhbymxnsjzjsttvvacnzaliwaddeyoxwpmopvdnqkxjvffisnwwyhhvyrepxjzwmhzzpqoerfgzqkngtcytvtufreqbhbyutlgvrgtdrtekrzclgkisdmvbgimsvbtdekvttcjabqdecnlswfwmwwjhftgvslxysevchkpqawxiqbrjcrepconkeouluueqnvhxacwbrmwzobbqyrpvvexoqbskobhoppnyrudbdiewmaiipbijhoieeuqrzkwatwosyndbrwbsilhxvxtecefmcovghmpspmjfehnhxzfzdslpepbouknjmirbgepeyhqdailmgvygikoevfuwvstgfrzizqosiqokebsbmcuqacaccoldjcyvhqhzrhccrpfmefsgbukspuebyjmenqdsfwpjsawqgdzmvhudjgijbxgjzeoqvqvqxgekbpxnrkdsuwajzghcxetddxjwakpabectgbfnzgfkjixaaatwogwllelqjowwcqajotiifjyexfjugzrfohtdifulmmxbmpogesfojdytckpjslzmuhtaqxwubizvqkfjmeanvcnbzqjxwbdiiwamboxgrerxcbjiajdkjcxnruqoebllwfxmeibafrlvcxqjtzhhimiqgdfyfvneeonplkgelfwgwnomqtychtbdffvgxfzsihbfdqqlgiwvmyrnfdjfkzujejlyrfzcgrwkgvvmvzqsxepffzkylyggxoumvczppnlpqxsgajqvcraswicfgzlhfmbbvgheecnquozstyptypidxfhverlojsednujcqzyxbanuxjyssxvhtdougahbvhqxzczvbupgbxeztvaiwrsdgfgqitfuitjbyyvgblcfmwlirrgfknecilmawtkqxjkvjphinfiipiuaccdhzwliqmpvfxjpyibbvdcsopdhazkahsyolmqkzskdaxmvuurmiyepqeejotmbalmuohvnbgqrrryyxoyarggvdhhcfysvryioxfbyffmlunmiptxebijbuybenicvjrlwurymwfpjdaiesfmyhybqeweklmespoyavsdtexvaroeaunmwkivffmdtzcudlvhpczkefqbqlvqbjaghrzohietzavwvxxvedcjgunlhxsgowgbjzlwsufzfhlocajuhinqoqkwbpxsokwamhyxtvoivhukrtufpvcxhhwuoeawwhpasgulxvpxqflohryyknkubkceopapepkmzqympdzxomwzpymsevopnkywlwrzjykjrmlysebsigfiggfheofsatzjgdfzdwjogsfbhkpipjatdmhfqzxtpzexbijdyjdnriiievawzdfnmvxbtrqhxbvxgqtuokdtshcwoatauavwkaanwmqyjsbmvwtwxqquhabvwkkypepsixczqrprvivtbsrkubnhcraqykmrbpxjweocaywkwqqxwgumbnbsvotloekfkgnojgznmnevnwenslidezmivsipxskzlpzdfhhudzpbdxzwrjbbnogbyrwgjabqqsjdfyltfehodmpubkeyfnwxwdlbpayxogeanmghahqsnzpabyxacojnpzpueemylkoqpzmcidinwcdeepahfbifvkbrqlvnymzzqekikoiebubpajsfnlmjxynaunxhkkwcglfecisipcsqaypijzjuxnjlqnsfbmbhcxwsavglhsrhigjjsdqldfiwayvshrftuoxjwcvrmhvblnvmhtgmrpkvdscpzaiyqdyukfdwwziavtzoyajllgrcmxvwfzecfrjkvwaeahtqrqzviduvskrbleprfgtvzovdmrbelczysfdzafwsudzwemftlgluzteyzmcntqedjsqjwensvweprwgvtvrzjgavxdxbjzzifjxzbkcidqfnooxonbyjunibhprhlifcsrnadoukujkmtokwbdgxhvpbfumjeuzahtmnsbrvkttjxziumihncvibcckoahbhaphcpggjseymqakdavvjqaczlwysrkvextvpthyfutaetngqfduboilmwequaukikdmcomrdsfellscboolthxoixgkwzduqhsydnnygeqhjnnhwiiqhwxrpgmhqhfjxvdrifxchcczesgxmtbspeqlmjuhymffvkcvznpznjucvzngqgrxxvgvxbocqfwttehpkqqodjbatiduvtndxmujhgncetiahfzkddfkikptawxbkzzjensuwufoyyqfgzlkpfkazaskgevdeavhfcjtzfikwftaafpprclmvnuraehcunmjgdilcmyakzpwgvprnzwhheswfgcwejtdazfqqbubibsuplneetigxnnqzjbbyqsrsndrujhfukxluvqjwyihynlbjjjvnqrwusefdxjqostnwjhktopvmneiwlsqriobvjqcyjbrngsgsbcuaapxcqltkksshnsarzfzizlitonubgtzrkkhyoywqoyrfdkralbvmepptkajswfjbbymlodawovvqhcawlqupaivayazohogwibrxednbfvrgslxxgrjinjeqyyoidgisbvaoltxtghfmmrpdjdlkjckwhmjjkmajbzalglcpedtzwyoktwvmktnfdncbjxjbnzsmlfozuxgwmxmqnjfqjbqpvzxtmzzycapddkktndlmrqizldbzaavciitdxkgazfftnrpjrbhgvcmrclzdqccosppcyjwuxwnnhqfhthgrwfzkngchoyulklgolfhobikldjshsbnuphjerjortnhpactwruunlaobjfclmphsixgsxfpuizyonduhoqmncoeoxwhvcviyrpqehoanvaxsnvdgwqryzmwcuuadecpvsclxkoitlgyrochrfeidknrnostmbmnfjdcfbvclugdupenmdqcaudsafokyhczbomavdxraivgwkcwmflsczponlywoyxbxufvzpmzporubznjymwcatqotlinabpnopyvpaxmfsmuspqakozwyvoyyraizusgcqukxbdplvfwhfjyypesmukjvtwdfwdtwukkjsetcythejsppbbxqwkzqhfgxzznhoqgdmytdlicnjemmdjjolfbczrvqzizuuoklcmooguozvksarpkuvqgqzwacrjfenvpxwzmqejjqgerpevrmthixhbshrlacrlvxvqonjydlzclmmnmiaiaukmsxaabragyvizjmhugkgjkdfyjoywrycrgeoiqsodnzcgrtwhbpbiqfalpvzkcitwjcgogiqlaemehhuherfyxegnoapqpxcrwhptwkeebzrmvsbtzyyprhrbizbpowlmurfnqptykyeqkyqtrbpvwbyuonoijdzhbgxphgxaxqdsvalxoyltmznyquchxhfudtctwwmkxzjrixgcwfaszgnweopimmjzbznjrjvjtbrwhclpgmtkrzsycqwqklhupillpskebbhlqssmakdumzpuzibsciopfvwrlkietropnwkputlrllfmtpfigkyjfmjlukqotugzqndpviipusaluvdmwubithizeuhfvyqtyvtltanazhywrmnfqxheehzttlugahkmhyuvgpvbtvilqauivbaclcptvrtwotygxlopjcqxtuirpldquwefibdulpzkpavfjxdioypshdpcdplzwnfznojszggaigdlavwupvvoyaewuevvnfmmkrscjhkvdqxgatthiruwzswgyumkernhdobpanbifcpuwecqxafjlbgkeorkriwctvbxrvfaafzendmigwqrfasnoaqddainzuryzmzxmvudulathdjnzfxysdikjzzfloornefbdwajzuydrpuulodrivwndaytunixzsfqbhoabazslxdcqkkczfcdtmfxrkohvaxkhqunbuljmuthlqojrxzzxsuzrtnrsnnooyrbzxglrmscdxtngwxxxcdgwqihrvsyqyohwksatsrylikstjmjfrxkioaqhtoxxkjztyeuxulmfmjsqqxovlwctjbndfvjdjxdzveuqczgssidyfltsitaogaejsxsigbmglyvfvmqzktldwqcbzykrmstwkkxvdkpsnsjqpcbgupghjqokknhaxcodgfmgmvsccymptmiizkdowpegfbmuqnxexgyamhynjdihlptvrpuenkqvvwrludyoilyrkrvyazeqpkgojhdqesecdyatztcwqsqjuvhgiafntuyerqfnpzzoqxkrpuemkfaxwuudtcncrqyzseentxelxfvxelihnkmaetgosrqzlybnigoyfudygeknupyashjzjydmlvbeftnkucvsvvjqjkzesshhkttjnurxjnydrmyozkxhqjtmxcaiphcvjwthvraodjrxcpthkuosqsphewmnteirqkscltemixutwklutgahkkfnoqfbdhrtfgzpuyytdxnvmwcrcqwlcmomokwvmevcdcjzkuukvjqnsrzsntnyjsrjwcorcldnmytptsbadqfjxyvkyhqwnvmdtdbnwjqavszormcrgekhvumooushqainmjnsmgksvkrrkjhybbjsbxkegbifahaamayykhwkbmqrawgmmrgcaoaljvifnpaihejvevkmbcnkpmihqgtowhlyqqvovveozdgyaawvlpkyniqovonyqqzacfvguctrruafppkqejtksakumqwcpwkjziwtabedujuyryysvyuoejxknqqzjithifvltdxydazozbkonccdfqeqvcolwgdackiqkpitvvcncfgkrfyhvsbzwmdcxnklguqrdnmkoeavczwuxiosxamkjytgpsxgidjgtqwzysxhyjunrzkaxkkzybsrewdebnpemzoswldzgelouabxgvctyhswgmsrtoavfsdhnvdhqnxchrtoqbcvyskmzdailqmliiyuwsiaipjsroiqswvjrejtkdsskuifafphdugsjdyicycpcyucuzxbhhhjpgxxyphoddhdtwmrvtxlqhvbgaeonywqlgshofihaipxrmbsvxzockokelzyixrmigencoiscrvolaolbsielzeytctiznwiaavocorhggchincedilqanigqdsxwawacupeqpprydkhomlozwdkxvmdvcckjhqfqwdhunqkkkhgnskfaildedwffelzixmwcprochpybawuztwbnygjaepsqhastdmltlftwwdwivofyuhepalekzapztqdqkbxrkjucakngjftoxjejkcbapyqocvxfccvvbihdhqtwojdtyplkqhrtbbbcsjfymotwmxfcrvxwqmkbdmndhhhgebaybdevujanwmtlbdijshfaqeiwrfwdhljthoweotzefqpvqmxfmjgsguafwvpdqqcvzazvaniflvzwwdjzpurddgdhqlxiqvdcrdtzeiuzuhvrrbaugqkedctuzybpygspdpaolugvnvxqacqdshabauuvsoaqfdplmpjnfuooyejyhacspyozpeaqjlbqyboesedoldrlsgoxneleiyrqmmzswolhnyzqiqzokxyuxhzhbboibzrfeuuvpwxlxxiuszdnowvhhakcbwobleewccjsataahndxonzkedhffxnoulnpdvuvrcmmjvkabouyihloznpfxigztgisnooyejuktlvnohsnpwcniuqqtouxvqvzckefsnkfkhmfcqbbtslrcolgbetcbqhjzfectddiyglumixkxtluqwegdchcywjjoohlcmpajojtaxdhkisqbxxcpkxolprajanuewhivzqifuuersixrlplhvtegrtgcyshhpsbtuckaqwwmtnzzbxvczflukbpttkioseilahdznsguroekkujisnxwadgdisrniqopbvexcxrfdbepcbqlvofkxdwwlhswihlbnrhvzcftluchdcfshehllpgagmneatwfzwhwngwmzekmorjegrkdznybbhpscptytahzohacqpzbufplkynestxqydswnyjmzllwqvtdbrzvsvacetkndvanvpzgcyihovowzbaukxvbmwdtspsroleogpdcbqfvxqzahvmtdptawjdujsuohfxfudajcrrwwfwlqnekhxhstsiypcwukvqmdefylyrdzcnswtbomehkiqftgnstabnndnjzmdkenagijqsqryptzckulhlahnpaynyebrdrgxbixvfompzgeqmqfpoadodyxlyuvxxoqdtyrhjhjnpmulfcaifhikvbrgffnljrgoxxvaqznaljqewnemxzvlbfwnfbxeuwlituulydyldwxrhjyclrscurtmqkblbujfabdbydhlhkpbgxolvtvsonynizfufdqfnjkquojqxqixatduwblelwndusvebllrqwofcfqifbthtjzhauvaqxjedudoywmgeabpbuuxbavurpkswgulokplpwkowqerlsvsolnwvnspdgzzucfucfvelpedgyonfxypqtivqffiqqhvjatngxdfbrcgeiukgpijarqeirdqrqevzdfdpyyrkflzgsqiytxyrpngshgojvmayushwoggqhpbvicnruelgapfhvqxmmkywzossnzyannddarrhjkllgcdlsgjtyykffmkmxezihxygeraopqsruvglgrgehmzxdqrfymjijnftbkkarmzcsblionmsszfwmpebibdconajzisdlqzvraiqvgcdnqsehalgidsmuhzrwrsdoopskjfbexoegnunzbkcukduqtxslbqqblhcdujfmfefcgpozvvderdendtlvnpaxmvjmzsmjwxxveurljzwfppocrazypgjlebeivxluxmgajtrcrtehskckbjcjdeyqrsbbgcnmfafexvqfjyctxhilmyvsjxtwlevtlxeboqzdrymseiwtakokozyvkmpckjhwympwwshjceyoawuflpdcevizbwlvmiyupzfxmembggcnqlbddnjynhzkknjxrurxxlordndjjwgqbfdkicptvioneieuwkzpdmhaihpvqeernjxclyvvqxltdylxghdrtviopsthrqbereoysiwpdsvylswuhnnpxouomcofdjuujloanjimjaeuxinalxwlahbigqkvwxtfoarqzkzriunyqegqdfwmulmhqxziiwivxtizbbljbstqqfdycauteotzggiqmfexcsudnnxerdvihnojblnoacgwczldpgowrsgkjwijakyagizayoimslpqntljdjeabdtcqlglchxsjkdepmhvbgyislhuwqkxbtixoqhheerwwtfsjwlnyldkytnrlukmbjqvhbquxgllgjzhntpxjcknrcaigexfygvyizucvnexqqqcdpqjcikubbspurvkzbxfqevyviioyvonvtxfmdlcpiysxpbcakdqzegfrjwwebtbkwptthaxqcrhrgtjrolrppympiixujmtrohrpnzikakcvgimdcogpinqhchqjeniqcojzziiiqeorkkfbkextieofwrnugjjyfzrwvcuvfkdqxlrvdexlsnddatcznwaifxqokxxfkhhtgfvhasgjcxbvnynypwygvvavkoscqhyktulgorqtnaxdghiwsxelwormdwijfssvguuhhujpkhudhgjicrdnnfxzpbrtinwuhttljsftzwuyhdjihwyosehuphcqksuwpxjqzybjgbcidxaumslixgfqmmgqffysyitkdvtnbczsodwyrzfdsdbofupwqxiqkywldivvohoppkijcdptiuleivqvfoayohlzvsxzgowlsndyavsnfhleepzdxbbawiuicohuxrutfkvlqxhuffejkmyrpjxzkfupllqciadtjhnuhukghhzxoiioqrxeydeqdmivbdhzlrfalyuxsgkdoaiupgatfqeqghlgwbldqvxidwekrvsnwvapofjtxptoltvackkljsaiqsfolxydobuqwrsgokdkjemdrdrxieimulmiovmmbtuazjcepfjiqzorrahguiycsonesaxlmzrkeoxywyxddqwkiyabzhhxjvhmynqcdceietyekcxopskltndguoyaqsktptlhsyfqvfqrnystedyfogjrylanbpiwavidpsgdgvhfdesrtnoofydenydyimtvahliycpausyowmixnxsklbgldgqnijlfxoiluqrlgsedgvervafoclccinzbrozmywecbincqwjjasklfrrmkwsoglmvdsbvsenjvspadybytpxeypogmoncakpvsogrfobhnmdswzhcxalxnrsiodmmjmusamtooxkfmmwxrreejnvmwavgqzcimkicpbaofffhfkclxjswobvukmkorsmmbsbztmmqhswvgimmpawgbwzorprefkiolqbclpxvvtqsuyxfprapedncawrvwyxyjludqzdtbykkgzzxelxezmieehvesbaxmpafbanfdfvdmtnoffnxmcefwvgwwdjnuzygxoeddviemzmthatigvqijiauupcjpzeiehyexpfmsvbjkvsakzljrlcvibcqvwcmovhbnthjewzsudiwhqahnayhnnfohqgdndnigbolnudwjjffvivjfmdjtsakricvfnyfcygrtwlwggqwlvrfuqwjgoumbldgqgehvmhxnbyxtoiaaxgxhxhfdqykaevpinuhklghpvgzkabnwiwcwodqwisyrkpyowstigluvebgaiwttwnzkuvmfcpmsuwasmbmvnlposzbupkhzpfgygbozivmejhhyvjxshbuuxbvnlzqwzbhjprkaqeogqxzdnsmkrmvbdlclnevjffzjodgkgisbuovjgsnmuhzfarvjcoxsxqjzcllibqcoihkgpprswugezllabltyivzwwieyfqldjkkbyfppusznvnsiwptritmoyczwnipfbllautpeydblqazgvydxesdgntkrvlrwxnujguqrrfnolugpxwsvyhivhraenemzxyxxcktrmhkepmpovolpbgmxblpysribkximfjmrbrbfufontaangpfjdbqkcvvwafquakdwiqttlqhohsptfyfmgvhzenghofcwzbnyonpzgcsgmssnscmoxveodvaldwcskxdrhpetxzihdoqghvsuxrwylvztmcyunpxcnzurokeffdkpeiznmbortzczkmbjylzajfeqjeacsniqpjyoebergheioyfhfucgpolqsykwdwqnuwgbymyakblhneaeowplgyewjrefkkxgiunkhwrcdoncooaykfxzylfgekejarojoxhrtrzkxpfysuhhezobuvyuxzcjzelliywbuohxgcyegvzucocwiihfqjbuwpulxngaxrrurbcytzwopdyippuyxhjruojenbzcjvvzjpctwkuflohskasumphpaxfkrzwqhheqiiemkvzlbcghypfmjnsshqrthxajdvixxfwvbhbetwxvaeqjduecehfzkofsobchrdqpqaouglovhjpckuclgjnrufdmaqfxookndntemsossbgrdahngewypzlhcwxirhyboeihprbackuiojvbleshhtetyrisexickxtvtxwuyajksnuwqbxuodjzxzsnxpuptqnrufwfljscttnoixvveiutgwyzcyubbugwoipreroyphjotjiefupxsobwsjdfzxurjdodxqspslsuotgltvjjmpvrfxrzsfbsjincvrxqzbaxnblvgvhkdkkjawfdlkfryipruwamtpaqpvplyexlkzqctteexoysmofgpthdyehcqvsvxpipqyiofnopxotekdbyspqroopohkkzqcoikuhvktwrgrqncgvsevlawkzcuudxzihfjnlvjvkuczvddvuiabgpfrmotfebhwtlwigzyikropxnfvtlvmzkzomltvpyoncybbdblyytyycrfpsicgsvzksqgemejeetvaxravacbyspfoylutyryzcewfadqhsnqlwwhzkvhsweyvvjcxfmmceqdecioftgdtuetdllhvxqjgxrhtnwqicuzvebslytyatcqlwldvbdkiyncvhpcaglnykzarxvylgmhabrygigthtuihniyrcaxfcukuocekcglwoukubxchvbwvvcpjbvfungoyazrvzcirlpafbwjyhjizxxlvemozkbwahbndlukmqstsoncwyivojibarktzzxqmepgwrbjjtperuhjyychghelbihbsqnasgnjuschbtpgssfoqwqjjicfdzrysuzlvhdvvqfiaxgohuubjemhxavfucupwmmadihyhtqcdzmdlgabyzgyyjyfxbydaqurffmggfzdfnnqmlmllaousvupvvxjbyxddleyudclwpzwdmbnrnidgrdidszdjgmkggzlissorrwjfddgixeomcvwklenifdhvgegyqfifxzstwioxcgoswuqjtqywwquybujwhiypebngdiraqcueeekdkvlgzzsaemrmerokqcrqfhzjbuvacskujlbyuptandooraxnqzoitortxakjivjndbflestdctbrqsdyruvwzujwsaeldfhhcdbfpqkizwatggvgpikezneqpuryzkdkczjifemhfnccwvrulifqeuosnmhwbkcfaeqbpetlvhgigifjbmpdfivlzatdshwxvbvyybpskrdpqotyipxfsohxlxwruavnbcjlsbaciogqvkjjdowmbcnkfjfltnriwqemxekjbmylvzvnrgxeekdepgkfpoitperbwartimmkfyjxpmpvwgcugtenpacxxzymybrtqtfduplmpktuivwnlxwfrvlqyorhvoavytaqgijhrgbuynfldqtlxnhpfdvlbxzegjkyfplxnxnhwexypdfudtyxjwsudxkzooidthzkuoyqnxjpszyynfzzmuaofusvfqcvxhrbgofeyefwpvplzdzydsyxdaobdkperkxjugpxnzepxkvhaakkydzxaamtdlvcfqqtnmgkqbxekihgigxelmgnkqpssdhjjbimnjboboiyxfsflnuxcpqrxoejuflkfjwicxlzdoxxpemomauofvdhrohocaapnbjwbvlrnscuunxfxhroqhfjcgyaqqnwszvrxqpqdkjkymiygwcnydbukbrbvqdtkpjyeeqkxiswkhkrxcricwhmqsauiztyzieubkgalgduxdyxermeknpiitlnrhocsecfzrgagzsrevawvhtcsuqxccusudzrbbtgwkdwbkbtfklshcapanqsnjggugrhywtouppmeaheuwpriffjmnicbyobgxhgexmksnurkbhgmahheuudqaulkmyeubuiyakpftlbfcnnmframtjghcyeegxbngnwmifflhsjnsgacfmwgtcdzhrrflolqangavivxmjerjfhyznewejvtjvojhvprwtjdroxvjpfzfcrdsvenkvgqdonxwtpqvpmmopdvnatqksfmutmseevwtdrpgsocgiyfzmdtgboaadmfmslbsfcuvhcxwgpqxqvqujrkosfduvxfjzfykonzwqvzvzxkzqigppuhfcabhmmlfdvubqcbxehywjltjyprzusjfpvmpisprlyszhpeyyjzzorxtfxlalefpszblfkqgxvgiubroswiwaaksmbhfohtqswlstrkooxwgimdwymiffoijobsqhxocipnriklewyjofhszrwrkjxxryyyfsdachjreudpjcqdcbhefxmjagzjkthrojpwmgymdvfuvyqkssjsnnwpisqkfmkstmbdjoeoqblyntvvhkiforfhifvgnwdtxtqdmwmjyouykvublnirayriijgxokgwisnvgnucdxjhjhzqxxgriablmloyzbbypzgfgwesvkwjbhbkrhnwxwarchejbixmocevuoidpkqkcwgbdqhmnxkdngllyrkuthaxkpyzpcuqqngipinovmvwpduzzfsmrvhrnamblypfmnrkzclyuggwgwtltmzruyolblwvkbytlbjryukcyknrpofhevilgzkqoxzcysydycqxttegydqxkypovobxvohxowrgnjxhollloxxmvqpidclnrwwpmisswtqzoosgvjkykfskiqmevegieatdhluvrffkhxinqtbmwvrprdjdfkeadrswkxygcvnjycnshbnbzlrohwbgimmqzcflwgzpdcmljttyzswzhjqjrdkzeuuauomgfvbijpxdvinhvwjrydoilzwumsuqtssjvlxojbqldlxsfqgswbuteejiahtrxjlrmefchfdjauockaewgziuvxpxvubqfwpsfalieclziczxthohobdbcehprhtfzcpwridippqekavvbkimmzphaajzcptduwjsqftcgbsqdwlneannbbtosvrafjwrjfsfabmourlzjdvuhpqeznqniybrcnblecnrdpmcimlxmtycvhphrzmltghdbgghqpkqnuedsqxykmbuuhgstcogoydumkaomtvhpknjbsygztkadowvqiptpnwwqhmxmepbfexjammwoeuvvagsbukxzosrvzrsheujrirwzasokqpaktgjrgqspgjnvycywucyalewtncynffzjahkwrcohbthdkxyvwrbazdsjjttwbrwjyphoxtqeqgnjlhypankvvfmeofieemcvgpeqwtjvhjklpgozrcdwjptgdhlsuegnqhmgmbjndcmsaupemiqjhqoojyeqtlytdejqbmktlpfqcvkagozgbeejxalkcfxzfjrzxipbhiwbfnhyokaapigbspxattkazejeiwlletvsnbkphalnrzazfwnppydulfiyaeiuyqppmjsbwjznhjiqnzrhiaifunigjitrjcgcjyqrzleyvnugsuzygdqodaptpzhzoxywsrghkzqpljvktzcbomugpgnocogbaryhahdmsvmrmdpbeqgiobgwuptuppppsbrvrvupxnvfcunlivhhnbxtcbebhukbvyvvmhtcrrdtqlmvlmhhcbeplsibaxhyaempzolhfcsxmccygkwojjnarmzehpixeqfhmngxlgcxrjtbrbwsemmtjmmysvpriawtxjgoaiccdmwcxfberbapwycoplmtjfavmdtwtorvncgwcbdwznwhlsfymnadyrsedpnibafzggvybymyxpcglbbqyrcogjntkwgjxboikuskrkmswigopiqfpuyvlismrzhravhujioylsdtnefsjvpfefkqoiajudnlxknllfphwiqyoaopojnrpagcdtuwlduqtufpuxxvbpzaxlavecohmdqqmhtdilkddjmraclqpbgzaenajssnpvoeowmzmcjmaxlnhuoyrnqqaqvrkswfvexzdlrhrxzplcwfbemlaoagvjxohwwpgmjormlucxaeqfcaqgszgiavokanoomwxxhrzliatfjwxsncjryyepknrkbwqewdkimfmoabppphnppcpamecapslkgjgqsohbmfpeixaugvuaeaqsgaxclgufjsbwehjlarxnblyryzlnbmtproblkuguflgemsitlslxxovxtellpnwqoslkrxrlmosxvxhuhtwskpblbjseipppiprflvdljugbezzjinncliuswdtmrmzqkstlinyxjvkmegwyrcpoujuozsefcscxaxeosugkmvxcupjyvyijdwlswxizzhfsxjinexdztvbslefecbljjhrlutmtrqoivhbpagpcqgjmtbetmwarhxmesmhbeclpbalsbxkgsmjyytuwynkunhugojivvniysfqofccqyaekvcndrkdubrbbpeodqtdqeebiwgzfwtyofmffbuqkgdtivuyfvqauihaspbecowgluhqnfickixbkskiyqejvqptsenrdfbaouqqaangrnlxaskfwlglpobdyafdverlrsdsxycfiiwwjpaljbqujeqjoezilfburkivrexsaqmeyvkprhinmkvqkkxdcfpwvmetgywarjzaxharauhuduecocwmpmgwvrpbbkusyxamrkuigwhaxlrufiolnctvscthrmxthbdivhggeypjsqhkrzzswvvorzgvlibiwvogsoskydhijleeaikmpeaxcytccokanquirbkegytqlmsjlttynmozlehauprkcmxeynzdmsxbxjvhasqwtsieirfauwxpifdciklqcwxiycwmgulqinxhnbzufzjbnmbkwpycjjkuolsfxnrzwvqbvrpaykvddylehrlexkdxqhctknrgghqtsuzimpcpkjzuqgfzaaexhtehmtuzfhvriuyaoyxgyvmibrwseruawlfabwszeukixxfoivkmmncnnejwposwqnycgaytolopuctknniiebxzpgtyyltqpprekbbrmqbflwawimifoqspcxzwnqdxgnpcjarsaqehzhsntvcmquxdjjwzlmixivjnllgmbjkwzxvvmdjasnukmoerjqphmuvatpwoildncsrzgwwcyoxcidxdkoislmuinhjmdowhzdnhdpptlyvpiusreczseilrqiwpbgqtafkwgfnwjnaxnjkisbgagtnksturmdhiwkxaqadwupoawaaigjhefpiexhnqdkijxcpyvkssobcagkjadopuwhbmnscuagwjnjrfoogbhdudrghowdpumnxhlqejlgrteemfhdovmtqpmxpnfthhbmiednkfvegpnwvhojbtdavgwfmkpetdyrrmayiikgagcbeafifxonpeockevwlfpkmqrcqinigqianomjtorcezfzhknpdpmnwvrsocqdkoodpxylrkitpltnkxbwefzxqqonlihcfsduastaicomqsrzlkbszicjncpwzjdoejiasaebxqzizsyxkntlyagpgcoistuejmhbehstbwdehebhdloqwqbyflzqdxryjypewxocllmmagdkugwnoamwmtklmrckvaqpiiljtucjwxfvzdrolwguwhzadiwmtnowhjfmooohgsdsqyfcjkedxrxttfynyysgrmfzvohyxfavxerxapjphogpgeqmpikcuyoysdvzyklbotpeyzvkmuhoouxemupyxdztxeuaaxzvncfxujptvevugewbojskkmlifhieolztmvzugkcznhdcseilwaefjvqqkqgzldzkmdxsykxqvotosayrpfkzjmfysgafycglxzvnxhjrlrtxeodkfnwjyfrizppntjngpypahhuhesgkxktlqybdouzyasngwgzlhfgikedyhitdjxzshfhzlbweevugtrljolczhaxecglqgqlhosgywgosuvrhmwxtunrpirdksmfrbbxlfgoknzaqgyxgciszicygndcncupbwpjvyzfywshppnwhjobcrjfzbyjrczcdalsnrwihkpibyznznullsqpzseotnukhfxpnivzrloyfpdauppzyiihesvmpawrjpszufdomrzygnvmqpjflzpdepmoyznwbuahrulnsftnwvtlucgohbyfmohmddsfuunohdmiwtihqsnmiwyxnfpsuhxiydvyjejjwaxyjjdyfipgtjrlrwbgycwvfrljokekkzuvlevsrrmhugedchgpzalnlycyzpocemrlwgakizxdxhhuwhxbcvqdjbnxlntuzxjoljtynfvdsarmxowothhcjpjwdedrjueiczvhdhvzvjlavxuschkxyidwnzcaucqhnxayohehheveamijgvzmqnubtconujewfnggisqpdcgymgfcwfqcchtvhvtrhpsnzdvwybovbgwunywrsivtbyfacmxjvjxajsplpnfttlnhbyxokskxnftmbaewjijqfmehtcyxnmdeackmjtrydyisytwbegsymsahlbveuyiybaabrgifjmyepdecqqfkykrgitfyvifswmjcezxcdtrczducxdyjiapjggejuxohkyxznmgrzhegyzxifejhcanbqnrhljgwmgtywcnffsvkwtytmyvccshycrjctiuzucfpthxnfdolpulqoprlzryjwvpfbfizmmapevylmjrlfidsghbawryhghumvgznjcqmtijllxvuuxpiofbuhdwyeforrvcyymmtwkfvkfomqybclteoqfifwoiedbxpncseeuasnemhcxtzqvucuveibywaacawxgplxfhrsqiyxaporvnulqmwwvxtrwhibuyhtdlktihzmnfxbcmzecvjdpyokkiizcecdoidmluukzzjrddhtdvwyeisxwsdoxgytgyqgjgjcoxzvzhiszzcpqjznuoguzpbhhbucygoamwunmicwdvjkvydvfmdbqqtbczugehpwcldknjlarkodhuzphnnmrgwrieyuxustkkhizavkvwmbseznguvcvwijciamzksgvghiqstgycaumqjdfzyedoqviaryszppvpnhvqfvkmbrnwvimhxgxdkxoplewqlswlwbjvrxharvdfvrdsasqhqzyxndztlgmftfkkteoiheuahuimihntchzhctezhdprgfpgfvlxxrcemduvaqifizopcbrolrkqkmngqnkjhpbuexfyzfyejsosmsqbpzhshdotksgnrgoahsljcnymhetufasunglvmuzwxepmdsuwoedlwndxsztgeesdvcyjrfryzibqiuntezjegjdiqaeogcqpzxqkmbaycmwyyzaonhxgexuplwfiodlcyoiacldyuohvupvmukksxmhgwliclayoyrkvhjvbsjjdjypdluoakdagphdsfncalpwvmaehsargabrmijhpvknumtjgtqzbpgegxflzgblczzqxnfglxlogvnggeyyjeebpaapvuyaxpwtrlwxytdagituuboemdifgehhgmsjkatwqoskqcjetochkmittwnkqnhahfbuiedpteumshslhtxmkgncgjltbqdijravxzkxxputqruhevuuqpdurguworxhxkqxcqpvfpwpvnzbxmjgxrpajzvdvtgkwoefwdeaotbeapqaqupkvoiykluxrpzgdlvftidvjryglmmkkjcttfqaryvojpgyfeofwigqjzlrnnhcdstmjqhjsojqdgndrdizjidkrpabztvnelspwacrnjfwxhbrqwcxtwiykpfpxdkmbkpioveuvbdmpxnfnrhpwksauprqbxcxdrfcjxruczzsdzprocrfhpkckjzvtodavodklpqwqhkknkrgqwbiqpyjikvmjxsxmwxpvxulovkrzpezdvbkbeqrroxdkzudnphocodenlxraarmgdzymbwavbscjxjynpeucanhefiatkpydsqaxoqsrsfryhrilsyghylpypsbwcuahobwmuqrnxwfscksigmymbajnuhkeksbcbqcfnztzahgepabbywkijqboolekpgfgdbckylcyhwwodxusesbbhkkpbtdslnhkjbfactiuwownbgfezvfhuyrlzenxeigtjoelhcvrzgcppchraxpurzohwwiroreedqnuowrsektacvzaqnjblakqxtwyfomgcskrygusvuxjrtbppwvartyuqoqammlqsldzstbutpkwvochacifhoferdidjgdbtzceltmdafjmzwvkdjwbkubbagtwrwbtlcqzimvnmcafixfwvfhmteaqnovhbcgggdzfodbborphlcwenrrntssgapwkqrbbeqishxrpqzgyapovriwktficsfppvaenbhfgiqxkwsvqsbqseotvbxytzgyfqhhvbyszmakksyzairweznjgkdwctmpwwnoppvqzfahuiyjoebswovbttcnqwjeugniaerjagzvgmtilhgizbtgozcgqgycrddljrvhenlnnqjqpuuplsyxvnyinkxpxujdheoidqvphvcjwgfqubgniauuiysrfnwfuijytgkfzdpbvgdozfnfliskqgnvbbvkmjgcdwqcmykjmnynjycbvsigpwltmamnwdprcuckljvoqwqwjksfofapwehplowndkflsrgnpjpfcloaftxqbsoyflfmoxneseiiaqebncnqinzvcmpgaajifjkaupuwgssgriafyfdzrbagkzmfgpuoaycrabqkzuslhcicpyrukqtqdmlorgvuhwdyobzjhbiqdtijdnjszpohctlrsqclhxqdcuqivkmxztxqehgroqcmrawccmbivgyeidliugietpmsxqxxvczeafmwftevnzzdsowrnracxzlogrwhqaqyycqhrxzprwlzagaaoeitlbkeivpjobgmogbpwhtrirpqikaqypysfhbdjjpteojddfftmabvbwhkrpozxbhbrvglimnmgdqasxkjzvpqkpzmcgflsbsshuvjremmrrtbnfknprxppncgbkybhfcgjsrdpelrqlbnqbumwolcxexjrmrdlggrxxanguhajqoaiwtykjfgtocficbhdhbtznfvlcapbvzdblrpymjuibxkpbwjsuheshpovkfoqyljdievhvcowtuykyuptdzakfcrxbyrkiuhrxxlbeyjcvobqsndptroqancmttbyyvufdwqzpciyxoabutzzhfviblyfausqpoakyhlznfjvjqlrcczubqwdfsavwogvifglkhyfglrrbehghbunqwrpmsaaxiovgxitnzomblnxrbyowrwggggzpizgxoucsxxadlmmrcaqtckjvzhssztiqpsqofsiwyssavscimwjwjcndpirmgdgjvyydvflrolgpqyahbdjyacwqjswlsfjrqtwowbygthdkgmyiurvnhwkhvxxaaidxvwbnfqndglqucmclnnqmtgpykahxcaizbedpyhhjcqkyvdovfrxgpnasncgqstokqnlwcoorsstxkbyprtnbtjxszmbscjlvnqihkzmqkqnripsxposgfedyjykrctynxerlwqalsjfiinvkunsnylmfldylitudkrzqsmkbltutwdpdqxounovmtsyuelvihmvgukxxedbzuepryjsqsbcmtzdgxoysgoaajtebdcslawrptvazfxayazcrxykqlxzaxfxiqegaoremtshgcewcdluvydrhwutcomhdcmdsopiuwvnuygalvosddsmmxezgqozfedlgidiwbkhvkcgesivrgvzmqqiavexdmdrgrffhxxgpiqwkujkjlcolcadshnfxhfnofdnmqnppqaiymadkuepightrfodmauhrsyvuhctzscenlqbvfxggmygvtqtvbhwdaoczloprvfwwmoiuuvbsylfurqobkifaidqqmhitgpynnnhmwyajqbcuabjlw");
    
    
    
    auto res5 =  longestDupSubstring().doit("ababdaebdabedeabbdddbcebaccececbccccebbcaaabaadcadccddaedaacaeddddeceedeaabbbbcbacdaeeebaabdabdbaebadcbdebaaeddcadebedeabbbcbeadbaacdebceebceeccddbeacdcecbcdbceedaeebdaeeabccccbcccbceabedaedaacdbbdbadcdbdddddcdebbcdbcabbebbeabbdccccbaaccbbcecacaebebecdcdcecdeaccccccdbbdebaaaaaaeaaeecdecedcbabedbabdedbaebeedcecebabedbceecacbdecabcebdcbecedccaeaaadbababdccedebeccecaddeabaebbeeccabeddedbeaadbcdceddceccecddbdbeeddabeddadaaaadbeedbeeeaaaeaadaebdacbdcaaabbacacccddbeaacebeeaabaadcabdbaadeaccaecbeaaabccddabbeacdecadebaecccbabeaceccaaeddedcaecddaacebcaecebebebadaceadcaccdeebbcdebcedaeaedacbeecceeebbdbdbaadeeecabdebbaaebdddeeddabcbaaebeabbbcaaeecddecbbbebecdbbbaecceeaabeeedcdecdcaeacabdcbcedcbbcaeeebaabdbaadcebbccbedbabeaddaecdbdbdccceeccaccbdcdadcccceebdabccaebcddaeeecddddacdbdbeebdabecdaeaadbadbebecbcacbbceeabbceecaabdcabebbcdecedbacbcccddcecccecbacddbeddbbbadcbdadbecceebddeacbeeabcdbbaabeabdbbbcaeeadddaeccbcdabceeabaacbeacdcbdceebeaebcceeebdcdcbeaaeeeadabbecdbadbebbecdceaeeecaaaedeceaddedbedbedbddbcbabeadddeccdaadaaeaeeadebbeabcabbdebabeedeeeccadcddaebbedadcdaebabbecedebadbdeacecdcaebcbdababcecaecbcbcdadacaebdedecaadbaaeeebcbeeedaaebbabbeeadadbacdedcbabdaabddccedbeacbecbcccdeaeeabcaeccdaaaddcdecadddabcaedccbdbbccecacbcdecbdcdcbabbeaacddaeeaabccebaaaebacebdcdcbbbdabadeebbdccabcacaacccccbadbdebecdaccabbecdabdbdaebeeadaeecbadedaebcaedeedcaacabaccbbdaccedaedddacbbbdbcaeedbcbecccdbdeddcdadacccdbcdccebdebeaeacecaaadccbbaaddbeebcbadceaebeccecabdadccddbbcbaebeaeadacaebcbbbdbcdaeadbcbdcedebabbaababaacedcbcbceaaabadbdcddadecdcebeeabaadceecaeccdeeabdbabebdcedceaeddaecedcdbccbbedbeecabaecdbba");
    
    return;
}
