/*
 
 # 1044. Longest Duplicate Substring

 # Given a string S, consider all duplicated substrings: (contiguous) substrings of S that occur 2 or more times.
 # (The occurrences may overlap.)

 # Return any duplicated substring that has the longest possible length.
 # (If S does not have a duplicated substring, the answer is "".)


 # Example 1:

 # Input: "banana"
 # Output: "ana"

 # Example 2:

 # Input: "abcd"
 # Output: ""


 # Note:

 # 2 <= S.length <= 10^5
 # S consists of lowercase English letters.
 
 
 */
#include <string>
using std::string;

#include <vector>
using std::vector;

#include <unordered_set>
using std::unordered_set;

#include <math.h>

#include <unordered_map>
using std::unordered_map;

class longestDupSubstring {
    
public:
    
    string doit(string S) {
        
        
        int N = S.length();
        vector<short> nums;
        int base = 26;
        int64_t mod = pow(2, 32);
        
        auto search = [N](int L, int base, int64_t mod, vector<short>& nums){
        
            long int hash = 0;
            for (int i = 0; i < L; i++)
                hash = (hash * base + nums[i]) % mod;
            
            unordered_set<int> seen;
            seen.insert(hash);
            int al = int64_t(pow(base, L)) % mod;
            
            for (int s = 1; s < N - L + 1; s++) {
                hash = (hash * base - nums[s-1] * al + nums[s+L-1]) % mod;
                if (seen.count(hash) != 0) {
                    return s;
                }
                seen.insert(hash);
            }
            return -1;
        };
        
        for (auto c : S) {
            nums.push_back(c - 'a');
        }
        
        int left = 1, right = nums.size();
        
        while (left <= right) {
            int mid = (left + right) / 2;
            
            if (search(mid, base, mod, nums) != -1) {
                left = mid + 1;
            } else {
                right = mid - 1;
            }
        }
        
        int s = search(left - 1, base, mod, nums);
        return S.substr(s, left - 1);
    }
};

class longestDupSubstring1
{
    public:
    string result="";
    long long int powmod(long long int a,long long int b,long long int m)
    {
        long long int result=1;
        long long int base=a;
        while(b)
        {
            if(b%2==1)
            {
                result=(result*base)%m;
            }
            base=(base*base)%m;
            b>>=1;
        }
        return result;
    }
    bool check(string& S,long long int l)
    {
        long long int m=1000000007;
        unordered_map<int,vector<int>> v;
        long long int current=0;
        for(int i=0;i<l;i++)
        {
            current=(current+powmod(26,l-i-1,m)*(S[i]-'a'))%m;
            current=(current+2*m)%m;
        }
        v[current].push_back(0);
        for(int i=0;i<(int)S.length()-l;i++)
        {
            current=(current-powmod(26,l-1,m)*(S[i]-'a')+m)%m;
            current=(current*26)%m;
            current=(current+(S[i+l]-'a'))%m;
            current=(current+2*m)%m;
            if(v.find(current)!=v.end())
            {
                for(int j=0;j<v[current].size();j++)
                {
                    if(S.substr(i+1,l)==S.substr(v[current][j],l))
                    {
                        if(l>result.length())
                        {
                            result=S.substr(i+1,l);
                        }
                        return true;
                    }
                }
            }
            v[current].push_back(i+1);
        }
        return false;
    }
    string longestDupSubstring(string S)
    {
        int p1=1;
        int p2=(int)S.length()-1;
        while(p1<p2)
        {
            int middle=(p1+p2)/2;
            if(check(S,(long long int)middle)==true)
            {
                p1=middle+1;
            }
            else
            {
                p2=middle-1;
            }
        }
        bool r;
        if(p1-1>0)
        {
            r=check(S,(long long int)p1-1);
        }
        r=check(S,(long long int)p1);
        r=check(S,(long long int)p1+1);
        return result;
    }
};


void test_1044_longest_duplicate_substring() {
 
    auto res1 = longestDupSubstring().doit("banana");
    
    auto res2 = longestDupSubstring().doit("abcd");
    
    auto res3 = longestDupSubstring().doit("moplvidmaagmsiyyrkchbyhivlqwqsjcgtumqscmxrxrvwsnjjvygrelcbjgbpounhuyealllginkitfaiviraqcycjmskrozcdqylbuejrgfnquercvghppljmojfvylcxakyjxnampmakyjbqgwbyokaybcuklkaqzawageypfqhhasetugatdaxpvtevrigynxbqodiyioapgxqkndujeranxgebnpgsukybyowbxhgpkwjfdywfkpufcxzzqiuglkakibbkobonunnzwbjktykebfcbobxdflnyzngheatpcvnhdwkkhnlwnjdnrmjaevqopvinnzgacjkbhvsdsvuuwwhwesgtdzuctshytyfugdqswvxisyxcxoihfgzxnidnfadphwumtgdfmhjkaryjxvfquucltmuoosamjwqqzeleaiplwcbbxjxxvgsnonoivbnmiwbnijkzgoenohqncjqnckxbhpvreasdyvffrolobxzrmrbvwkpdbfvbwwyibydhndmpvqyfmqjwosclwxhgxmwjiksjvsnwupraojuatksjfqkvvfroqxsraskbdbgtppjrnzpfzabmcczlwynwomebvrihxugvjmtrkzdwuafozjcfqacenabmmxzcueyqwvbtslhjeiopgbrbvfbnpmvlnyexopoahgmwplwxnxqzhucdieyvbgtkfmdeocamzenecqlbhqmdfrvpsqyxvkkyfrbyolzvcpcbkdprttijkzcrgciidavsmrczbollxbkytqjwbiupvsorvkorfriajdtsowenhpmdtvamkoqacwwlkqfdzorjtepwlemunyrghwlvjgaxbzawmikfhtaniwviqiaeinbsqidetfsdbgsydkxgwoqyztaqmyeefaihmgrbxzyheoegawthcsyyrpyvnhysynoaikwtvmwathsomddhltxpeuxettpbeftmmyrqclnzwljlpxazrzzdosemwmthcvgwtxtinffopqxbufjwsvhqamxpydcnpekqhsovvqugqhbgweaiheeicmkdtxltkalexbeftuxvwnxmqqjeyourvbdfikqnzdipmmmiltjapovlhkpunxljeutwhenrxyfeufmzipqvergdkwptkilwzdxlydxbjoxjzxwcfmznfqgoaemrrxuwpfkftwejubxkgjlizljoynvidqwxnvhngqakmmehtvykbjwrrrjvwnrteeoxmtygiiygynedvfzwkvmffghuduspyyrnftyvsvjstfohwwyxhmlfmwguxxzgwdzwlnnltpjvnzswhmbzgdwzhvbgkiddhirgljbflgvyksxgnsvztcywpvutqryzdeerlildbzmtsgnebvsjetdnfgikrbsktbrdamfccvcptfaaklmcaqmglneebpdxkvcwwpndrjqnpqgbgihsfeotgggkdbvcdwfjanvafvxsvvhzyncwlmqqsmledzfnxxfyvcmhtjreykqlrfiqlsqzraqgtmocijejneeezqxbtomkwugapwesrinfiaxwxradnuvbyssqkznwwpsbgatlsxfhpcidfgzrc");
    
    auto res4 = longestDupSubstring().doit("bwvzoubsovtdpokbjgubpkzsdmxpdxwrkjzjbhcuvppjowoaapfpaqmgpkflwookqdujdfqsifdbkmwqfumwhotpdmevmshumjcdquspnihgceaedgxjgrtjdxqacznaluiiwrivaulamzyecdpyfyxmiavwkqvbybabmshszoslhxzhmaqtvhbnznnxuyctrbywifcuguutkdxchpyxurmskwbygnbtatoxwesmtzchjlrnqsjxanoemmzsqcraykiszrieoaqcwcwlyorrcvlamxztujsglqcwjmqvcmmuwwjgkdfhfxfahlefserldejymbhgdddlwjllantqxeivdbrsbjdcsgrcngejbfvwdjbaffvarzdkizozlszqvzsyszqklvinaypeqyppcyafzqkdlreddrmbxwiikymgcqaghptuvbgkoebirotkfdxcfxeykqvdqlbmnbpgumksbsdwdbyqfdwdqpfustxqorwpxyatjuiocqjytiqzymfkyagtxqypmwnppqwpoltglrpalpextaglktgzauzwxnzgwqfvxitoqkiqcacpcetzscypoumazhyjtqhflnihtmboxmqqqvahqsukxebqnyxpyoiczdjikslukjvgeejnirpijjkhdjrfkjrvvqlrdpzwfyredgxljfjmbtrkpdydmpqqvywtqmdcyrtapmqwhkaocdzkamlbunnfhfcfpoechlqripwsmskcprihcnptbqyqxdnhewuehycuaxbzxbftjaqsfqtvmfvisepjnrzqibkbwtncipwcejllhlqxylwzmquwqgbizbumshhoxwvexjxgiexmjfsrfnplybfdouqggsntludnaznsbnloorlwkhicbzrfvcqohmlzojfdsyzjniyoinfszmaelknerpwgmctnkjjnixlmxjdvpxjjbonmfxrxgpxrculamkmwwnrxgsjlwdohonruecrtuknjjjgsmcctqdfsttcikawjaowskacuretxcdqnkapiiiwezklfnbayedclkkdwdqqsmxqupcphgdmaldcnidadhpvyvbsprbrqpifrpdsjgwvoxumxeuybmcwbmuyacvrfqfkuszjpwyjwbmrhbbvdmhwrowsqahmeexucshsvknchkzljwoztqgrthoeldityevjljhavuqcxgwzcoyvsjoxvmlrxtytlomorbfkskzkfzhbhqjumnwzbfaalogdwztbeirzxitgbmfcwkkgfwapubspmhuygtfhsxjcoklybqoultxvmtactpqqsgewzzguxndxouiacalpopiovashsfcnftuaxaafwjhruheabclgjjyxpaiyuqjybpkdzkyrfnxfwcvdedcfqiseljtebxzcjqmqkhyiurdiybznjnkzaqthrpanhflnunqucliwsdttzbkmndrckzucllnjosvryowfkielbdziuqhiilbbsfbllxjyodgurluibsfjxqoupbxfpxkjscslirbszjmhklgevhdrqykonnnekacqtcworjpgxuraikciaburspaldpihnyafojwmclckulomsyyzxonthymcffhlxjfzonzxpwkpihianrywxejbghxrvsadkhljtubrenaemecmmvesijfqpthrkhiqhdrkvxlrkciaklncrnxzdhcsuaesjmbjlupwvwjfelxipbaligpeojbrvosyimousrqaenebgeleuuybixbwirltnctluazywoqcefcrejgtlfruyiotcbmubuqxbdthtakywfopbvkysddivfaaqaylpoadazdskcuhklvuqmbguwtlaawymbkveoszsysramyowewkheriglqwqejursmaiyhmnrlxryolizwsywgaizflzghtammlntphjmvlvyujgfsjlscpjhavxbeutapfieswtpldeeuxetbqphkqibwdzfeqbjxaryeogyirhleulfeeprmshdmiikfhuqxxpxdryenhdzgxojixhcjswllduemothoxzzpbiapvinihgucazbvggihobmscpijwcavhqxlcenuqjjjpehpreyccucfiecnyflxojxdskncvvdpwzrlwkfhhvgcdeevtflgwypgvvuzlntncpqiczyzxoxsfabybcxlarysptirnzpbzfzlagchruxjfzibrwfyxtyydathyctagcnokpwqfiowsdjvfrnzogemfchwitmoqsoezqdkwefjufdnvnhogqzzcqngkgaiwoqofwjtdygktqvmzcwwmzemvxlgryjjzoyguwjuczziosldbwwygftujlpzanbszeaakidazfpdtbnrowhnlqgyvssziolsfedivgsqvamcliuqeemeorxlrzyofbiozdpuobjwuxglvuuvxebvsnxomfziirlvhuqxjwunehjcqjnmlliqkywwmguloxmapflwhoddpqzduyfkizkneooifsndynggljsfbjcfzahmkambrojzdbatgtimxiisguvdpftjcwmjxbqyaltbgvfefyqwnminsuqraztojpshmlrqtrbpyiekbanjjndnfkhlyihbmxvwyrfomlpcsbrkrptkfyapjctyoruxdwrzjgcrfsxytlripxckhabdqnxwyiidegjwsqvqckjhlmlvdhfnlclizhdpsvmsrkbrzahcuvonpizhyrwilmbmwexzzohvlhzfcqcwhfgamikhkhfrwmymvxrmbypdurouthrlzubtclfltanroeegkfjqqrjxwgyzymcoopcubqvghnckoccjdicffridjupfylgseipqgbshoesjjcjhpyodpituvipopeizgwortgqvotiyfzfnkixcsbuywrxowetievuudmwtnxcbbxpotkcuqmxczzldimrdulntjsieciuebztdtfftligeybplqculadfvnqqxdbrnjqgptjlhqrutfvsiencukxpioekrszfgryxsbcaqaabbsvskhpivnedwejrnooejfvfmozywtkntdcpphrwnnqdvnakujmrqymxgetisbvllvcszyaojatpmogehyfaecerykkratgouegtfsetpywknkhzgzmpdwkjmvimnpjtloqumcntnhqxnbzycwrhkxwaxhweefmrlnemyoeygyxrbwpkrtsbzqkapxkobfoytbhvemmqhnjipwsjenrcegvbbkwjjuckixszmptqbydsigpatqsbybivryjxfcbmjprfleoxhfpdpzwujtbbzunbuvqaxwlrfxsnfhsereyewipnradhqocwyvllxfsyvfmdxmntdjbkjhewufyackxviawolgyevjfitgtvaitkexckrxcwvhqyhfqkjrxnmsgavnxdwqxzdfykfkohprhmiuzlrhnkgcprtnixgjosfgdkbecvwhjeghxbnshmmzqfrbeaepzujjopmfwwgwdkguunugjtwronvdwthlzipilehrnfdxlflyspxdounyhjdkbmdgprqqebpgszrpjwpzsfapdtgyunjgzgvernvkvxfwnxahwbawjrivczeomcjoecuckeglrmgygpqmrpraujjbcrtgdqvhtszwulmwdzxswtwmdpmcuyqirrfujrcrbjpxnklyehmsifbfgpprdtptrjtaauoxguntymzlqroucijjaqtbdipxcrikfbiavjkpapsgfuvgojbdklidflwdqpyddgylyfpkxjpopsnlxpfhngjhpsifbdfpgmtluxrevxczumrddonelqdtzrtyswsokhjjybjlfkoxeeluioxrjkjbkfnzoesywvdegskgbnnxenlwjxibbzfuygcvdrijueiegvapxhrhsqsdvdstbjjmpuotzceluhiqxxhowtfafltqipugbbubtixdgutxbbfpaqqrpurxytjbomgsncnvsibaedbtmvnvhtfsiviotjzikmkahwckcjgxdovdhjynlhhplbkklowfyfwlaobxazpdeyjxaikvcujspctbsaboohilrgrpmyuvwmkrutzlrjjmsczxdwestatrrthgkewhfqfwfsigntrpkxnfrrlxszvpwvodornyrjpeepsdaoqbqcfoptrjbcnjqyepnumdwwqzrohiipounayuklksidvysyoaquhnsnafwxusqhnqhqdsguuuopbnfugprvblrpnykxegzqqmcuehhsmbxuymbbvddfjmqplxqndjtvkwpockfyigspcryulkqunugsxqsvmqxfruegmqbdhrpqyofhjuichixisrqovmgvsaitcwvbouslnqnwbxuyldltrsbdasafhjzbcwsholeetygedllizzxmjzfrnsjkpphgulpkiaizbgprspjfvwoivvfqafqhfrtpmccrjaqdqqnrrjidjvpmbovopcqkeykqrsdykrenmrmgrzfycwkrmajzertyobgrkabhqrhrvtswtlinrwjrafiwlggeibhtlwpaesbdvqkvrwlkmyxdfdzocqagjssirvhgvqqxuzzzborhilzmcuwmdbbxyfhoveudokxrtgfkauvukprmtmtoyprgnghqvujfhanwzogstrrvixbkwadnbmddidciqeshyfmmevtttyzldbyrkmcwcvghywscejheyaegfihroufxjzpfgwynwqsrcuqufjxftyqozyvkjvyjaxutnheqzwqftvidgbfnmirwqrxnmwfnqmqqqvflyekoakzfbcdgesabnaxlgnetkmqgobnyplpndyaahqfghpeginvovqdnknoimrwyttackovtkpyyuzmufutvkjpcpmuhmzxnutduwjcoycjolneqinpqmltgtwfxddaksdmggdtdxhdsvbclxiuowmbhdrmxrexzxbmzvxhpnjssdwginukazqbwddoaryxsgswgphlsjtylqnkqcfwrcprhashjjgfqadgbvdlmhqeutwsuuohzmpkbqhlmwbnfgurkryfeiezahdccpujbatzozvxwwshfhkpmvgdyqcyfduruseuylxgwjsxoaneqzaxmacwixtnsjbfqhvpqscbdxeuuirwqudavgnfsmiuiedqbshrwirrpfodjhicsmikoztytnsgncsrchrzthxnvowckygpbyybzqaqmzncyictygqpuchnknpghotmnlbioojhiboigybydgcfxpzpqsmuvorcojgmaeglnzqgndyytzowmtkntcfahrseijgnzjftsmezyzzbawybsyaspibinurjnnoqfkmlkhbymxnsjzjsttvvacnzaliwaddeyoxwpmopvdnqkxjvffisnwwyhhvyrepxjzwmhzzpqoerfgzqkngtcytvtufreqbhbyutlgvrgtdrtekrzclgkisdmvbgimsvbtdekvttcjabqdecnlswfwmwwjhftgvslxysevchkpqawxiqbrjcrepconkeouluueqnvhxacwbrmwzobbqyrpvvexoqbskobhoppnyrudbdiewmaiipbijhoieeuqrzkwatwosyndbrwbsilhxvxtecefmcovghmpspmjfehnhxzfzdslpepbouknjmirbgepeyhqdailmgvygikoevfuwvstgfrzizqosiqokebsbmcuqacaccoldjcyvhqhzrhccrpfmefsgbukspuebyjmenqdsfwpjsawqgdzmvhudjgijbxgjzeoqvqvqxgekbpxnrkdsuwajzghcxetddxjwakpabectgbfnzgfkjixaaatwogwllelqjowwcqajotiifjyexfjugzrfohtdifulmmxbmpogesfojdytckpjslzmuhtaqxwubizvqkfjmeanvcnbzqjxwbdiiwamboxgrerxcbjiajdkjcxnruqoebllwfxmeibafrlvcxqjtzhhimiqgdfyfvneeonplkgelfwgwnomqtychtbdffvgxfzsihbfdqqlgiwvmyrnfdjfkzujejlyrfzcgrwkgvvmvzqsxepffzkylyggxoumvczppnlpqxsgajqvcraswicfgzlhfmbbvgheecnquozstyptypidxfhverlojsednujcqzyxbanuxjyssxvhtdougahbvhqxzczvbupgbxeztvaiwrsdgfgqitfuitjbyyvgblcfmwlirrgfknecilmawtkqxjkvjphinfiipiuaccdhzwliqmpvfxjpyibbvdcsopdhazkahsyolmqkzskdaxmvuurmiyepqeejotmbalmuohvnbgqrrryyxoyarggvdhhcfysvryioxfbyffmlunmiptxebijbuybenicvjrlwurymwfpjdaiesfmyhybqeweklmespoyavsdtexvaroeaunmwkivffmdtzcudlvhpczkefqbqlvqbjaghrzohietzavwvxxvedcjgunlhxsgowgbjzlwsufzfhlocajuhinqoqkwbpxsokwamhyxtvoivhukrtufpvcxhhwuoeawwhpasgulxvpxqflohryyknkubkceopapepkmzqympdzxomwzpymsevopnkywlwrzjykjrmlysebsigfiggfheofsatzjgdfzdwjogsfbhkpipjatdmhfqzxtpzexbijdyjdnriiievawzdfnmvxbtrqhxbvxgqtuokdtshcwoatauavwkaanwmqyjsbmvwtwxqquhabvwkkypepsixczqrprvivtbsrkubnhcraqykmrbpxjweocaywkwqqxwgumbnbsvotloekfkgnojgznmnevnwenslidezmivsipxskzlpzdfhhudzpbdxzwrjbbnogbyrwgjabqqsjdfyltfehodmpubkeyfnwxwdlbpayxogeanmghahqsnzpabyxacojnpzpueemylkoqpzmcidinwcdeepahfbifvkbrqlvnymzzqekikoiebubpajsfnlmjxynaunxhkkwcglfecisipcsqaypijzjuxnjlqnsfbmbhcxwsavglhsrhigjjsdqldfiwayvshrftuoxjwcvrmhvblnvmhtgmrpkvdscpzaiyqdyukfdwwziavtzoyajllgrcmxvwfzecfrjkvwaeahtqrqzviduvskrbleprfgtvzovdmrbelczysfdzafwsudzwemftlgluzteyzmcntqedjsqjwensvweprwgvtvrzjgavxdxbjzzifjxzbkcidqfnooxonbyjunibhprhlifcsrnadoukujkmtokwbdgxhvpbfumjeuzahtmnsbrvkttjxziumihncvibcckoahbhaphcpggjseymqakdavvjqaczlwysrkvextvpthyfutaetngqfduboilmwequaukikdmcomrdsfellscboolthxoixgkwzduqhsydnnygeqhjnnhwiiqhwxrpgmhqhfjxvdrifxchcczesgxmtbspeqlmjuhymffvkcvznpznjucvzngqgrxxvgvxbocqfwttehpkqqodjbatiduvtndxmujhgncetiahfzkddfkikptawxbkzzjensuwufoyyqfgzlkpfkazaskgevdeavhfcjtzfikwftaafpprclmvnuraehcunmjgdilcmyakzpwgvprnzwhheswfgcwejtdazfqqbubibsuplneetigxnnqzjbbyqsrsndrujhfukxluvqjwyihynlbjjjvnqrwusefdxjqostnwjhktopvmneiwlsqriobvjqcyjbrngsgsbcuaapxcqltkksshnsarzfzizlitonubgtzrkkhyoywqoyrfdkralbvmepptkajswfjbbymlodawovvqhcawlqupaivayazohogwibrxednbfvrgslxxgrjinjeqyyoidgisbvaoltxtghfmmrpdjdlkjckwhmjjkmajbzalglcpedtzwyoktwvmktnfdncbjxjbnzsmlfozuxgwmxmqnjfqjbqpvzxtmzzycapddkktndlmrqizldbzaavciitdxkgazfftnrpjrbhgvcmrclzdqccosppcyjwuxwnnhqfhthgrwfzkngchoyulklgolfhobikldjshsbnuphjerjortnhpactwruunlaobjfclmphsixgsxfpuizyonduhoqmncoeoxwhvcviyrpqehoanvaxsnvdgwqryzmwcuuadecpvsclxkoitlgyrochrfeidknrnostmbmnfjdcfbvclugdupenmdqcaudsafokyhczbomavdxraivgwkcwmflsczponlywoyxbxufvzpmzporubznjymwcatqotlinabpnopyvpaxmfsmuspqakozwyvoyyraizusgcqukxbdplvfwhfjyypesmukjvtwdfwdtwukkjsetcythejsppbbxqwkzqhfgxzznhoqgdmytdlicnjemmdjjolfbczrvqzizuuoklcmooguozvksarpkuvqgqzwacrjfenvpxwzmqejjqgerpevrmthixhbshrlacrlvxvqonjydlzclmmnmiaiaukmsxaabragyvizjmhugkgjkdfyjoywrycrgeoiqsodnzcgrtwhbpbiqfalpvzkcitwjcgogiqlaemehhuherfyxegnoapqpxcrwhptwkeebzrmvsbtzyyprhrbizbpowlmurfnqptykyeqkyqtrbpvwbyuonoijdzhbgxphgxaxqdsvalxoyltmznyquchxhfudtctwwmkxzjrixgcwfaszgnweopimmjzbznjrjvjtbrwhclpgmtkrzsycqwqklhupillpskebbhlqssmakdumzpuzibsciopfvwrlkietropnwkputlrllfmtpfigkyjfmjlukqotugzqndpviipusaluvdmwubithizeuhfvyqtyvtltanazhywrmnfqxheehzttlugahkmhyuvgpvbtvilqauivbaclcptvrtwotygxlopjcqxtuirpldquwefibdulpzkpavfjxdioypshdpcdplzwnfznojszggaigdlavwupvvoyaewuevvnfmmkrscjhkvdqxgatthiruwzswgyumkernhdobpanbifcpuwecqxafjlbgkeorkriwctvbxrvfaafzendmigwqrfasnoaqddainzuryzmzxmvudulathdjnzfxysdikjzzfloornefbdwajzuydrpuulodrivwndaytunixzsfqbhoabazslxdcqkkczfcdtmfxrkohvaxkhqunbuljmuthlqojrxzzxsuzrtnrsnnooyrbzxglrmscdxtngwxxxcdgwqihrvsyqyohwksatsrylikstjmjfrxkioaqhtoxxkjztyeuxulmfmjsqqxovlwctjbndfvjdjxdzveuqczgssidyfltsitaogaejsxsigbmglyvfvmqzktldwqcbzykrmstwkkxvdkpsnsjqpcbgupghjqokknhaxcodgfmgmvsccymptmiizkdowpegfbmuqnxexgyamhynjdihlptvrpuenkqvvwrludyoilyrkrvyazeqpkgojhdqesecdyatztcwqsqjuvhgiafntuyerqfnpzzoqxkrpuemkfaxwuudtcncrqyzseentxelxfvxelihnkmaetgosrqzlybnigoyfudygeknupyashjzjydmlvbeftnkucvsvvjqjkzesshhkttjnurxjnydrmyozkxhqjtmxcaiphcvjwthvraodjrxcpthkuosqsphewmnteirqkscltemixutwklutgahkkfnoqfbdhrtfgzpuyytdxnvmwcrcqwlcmomokwvmevcdcjzkuukvjqnsrzsntnyjsrjwcorcldnmytptsbadqfjxyvkyhqwnvmdtdbnwjqavszormcrgekhvumooushqainmjnsmgksvkrrkjhybbjsbxkegbifahaamayykhwkbmqrawgmmrgcaoaljvifnpaihejvevkmbcnkpmihqgtowhlyqqvovveozdgyaawvlpkyniqovonyqqzacfvguctrruafppkqejtksakumqwcpwkjziwtabedujuyryysvyuoejxknqqzjithifvltdxydazozbkonccdfqeqvcolwgdackiqkpitvvcncfgkrfyhvsbzwmdcxnklguqrdnmkoeavczwuxiosxamkjytgpsxgidjgtqwzysxhyjunrzkaxkkzybsrewdebnpemzoswldzgelouabxgvctyhswgmsrtoavfsdhnvdhqnxchrtoqbcvyskmzdailqmliiyuwsiaipjsroiqswvjrejtkdsskuifafphdugsjdyicycpcyucuzxbhhhjpgxxyphoddhdtwmrvtxlqhvbgaeonywqlgshofihaipxrmbsvxzockokelzyixrmigencoiscrvolaolbsielzeytctiznwiaavocorhggchincedilqanigqdsxwawacupeqpprydkhomlozwdkxvmdvcckjhqfqwdhunqkkkhgnskfaildedwffelzixmwcprochpybawuztwbnygjaepsqhastdmltlftwwdwivofyuhepalekzapztqdqkbxrkjucakngjftoxjejkcbapyqocvxfccvvbihdhqtwojdtyplkqhrtbbbcsjfymotwmxfcrvxwqmkbdmndhhhgebaybdevujanwmtlbdijshfaqeiwrfwdhljthoweotzefqpvqmxfmjgsguafwvpdqqcvzazvaniflvzwwdjzpurddgdhqlxiqvdcrdtzeiuzuhvrrbaugqkedctuzybpygspdpaolugvnvxqacqdshabauuvsoaqfdplmpjnfuooyejyhacspyozpeaqjlbqyboesedoldrlsgoxneleiyrqmmzswolhnyzqiqzokxyuxhzhbboibzrfeuuvpwxlxxiuszdnowvhhakcbwobleewccjsataahndxonzkedhffxnoulnpdvuvrcmmjvkabouyihloznpfxigztgisnooyejuktlvnohsnpwcniuqqtouxvqvzckefsnkfkhmfcqbbtslrcolgbetcbqhjzfectddiyglumixkxtluqwegdchcywjjoohlcmpajojtaxdhkisqbxxcpkxolprajanuewhivzqifuuersixrlplhvtegrtgcyshhpsbtuckaqwwmtnzzbxvczflukbpttkioseilahdznsguroekkujisnxwadgdisrniqopbvexcxrfdbepcbqlvofkxdwwlhswihlbnrhvzcftluchdcfshehllpgagmneatwfzwhwngwmzekmorjegrkdznybbhpscptytahzohacqpzbufplkynestxqydswnyjmzllwqvtdbrzvsvacetkndvanvpzgcyihovowzbaukxvbmwdtspsroleogpdcbqfvxqzahvmtdptawjdujsuohfxfudajcrrwwfwlqnekhxhstsiypcwukvqmdefylyrdzcnswtbomehkiqftgnstabnndnjzmdkenagijqsqryptzckulhlahnpaynyebrdrgxbixvfompzgeqmqfpoadodyxlyuvxxoqdtyrhjhjnpmulfcaifhikvbrgffnljrgoxxvaqznaljqewnemxzvlbfwnfbxeuwlituulydyldwxrhjyclrscurtmqkblbujfabdbydhlhkpbgxolvtvsonynizfufdqfnjkquojqxqixatduwblelwndusvebllrqwofcfqifbthtjzhauvaqxjedudoywmgeabpbuuxbavurpkswgulokplpwkowqerlsvsolnwvnspdgzzucfucfvelpedgyonfxypqtivqffiqqhvjatngxdfbrcgeiukgpijarqeirdqrqevzdfdpyyrkflzgsqiytxyrpngshgojvmayushwoggqhpbvicnruelgapfhvqxmmkywzossnzyannddarrhjkllgcdlsgjtyykffmkmxezihxygeraopqsruvglgrgehmzxdqrfymjijnftbkkarmzcsblionmsszfwmpebibdconajzisdlqzvraiqvgcdnqsehalgidsmuhzrwrsdoopskjfbexoegnunzbkcukduqtxslbqqblhcdujfmfefcgpozvvderdendtlvnpaxmvjmzsmjwxxveurljzwfppocrazypgjlebeivxluxmgajtrcrtehskckbjcjdeyqrsbbgcnmfafexvqfjyctxhilmyvsjxtwlevtlxeboqzdrymseiwtakokozyvkmpckjhwympwwshjceyoawuflpdcevizbwlvmiyupzfxmembggcnqlbddnjynhzkknjxrurxxlordndjjwgqbfdkicptvioneieuwkzpdmhaihpvqeernjxclyvvqxltdylxghdrtviopsthrqbereoysiwpdsvylswuhnnpxouomcofdjuujloanjimjaeuxinalxwlahbigqkvwxtfoarqzkzriunyqegqdfwmulmhqxziiwivxtizbbljbstqqfdycauteotzggiqmfexcsudnnxerdvihnojblnoacgwczldpgowrsgkjwijakyagizayoimslpqntljdjeabdtcqlglchxsjkdepmhvbgyislhuwqkxbtixoqhheerwwtfsjwlnyldkytnrlukmbjqvhbquxgllgjzhntpxjcknrcaigexfygvyizucvnexqqqcdpqjcikubbspurvkzbxfqevyviioyvonvtxfmdlcpiysxpbcakdqzegfrjwwebtbkwptthaxqcrhrgtjrolrppympiixujmtrohrpnzikakcvgimdcogpinqhchqjeniqcojzziiiqeorkkfbkextieofwrnugjjyfzrwvcuvfkdqxlrvdexlsnddatcznwaifxqokxxfkhhtgfvhasgjcxbvnynypwygvvavkoscqhyktulgorqtnaxdghiwsxelwormdwijfssvguuhhujpkhudhgjicrdnnfxzpbrtinwuhttljsftzwuyhdjihwyosehuphcqksuwpxjqzybjgbcidxaumslixgfqmmgqffysyitkdvtnbczsodwyrzfdsdbofupwqxiqkywldivvohoppkijcdptiuleivqvfoayohlzvsxzgowlsndyavsnfhleepzdxbbawiuicohuxrutfkvlqxhuffejkmyrpjxzkfupllqciadtjhnuhukghhzxoiioqrxeydeqdmivbdhzlrfalyuxsgkdoaiupgatfqeqghlgwbldqvxidwekrvsnwvapofjtxptoltvackkljsaiqsfolxydobuqwrsgokdkjemdrdrxieimulmiovmmbtuazjcepfjiqzorrahguiycsonesaxlmzrkeoxywyxddqwkiyabzhhxjvhmynqcdceietyekcxopskltndguoyaqsktptlhsyfqvfqrnystedyfogjrylanbpiwavidpsgdgvhfdesrtnoofydenydyimtvahliycpausyowmixnxsklbgldgqnijlfxoiluqrlgsedgvervafoclccinzbrozmywecbincqwjjasklfrrmkwsoglmvdsbvsenjvspadybytpxeypogmoncakpvsogrfobhnmdswzhcxalxnrsiodmmjmusamtooxkfmmwxrreejnvmwavgqzcimkicpbaofffhfkclxjswobvukmkorsmmbsbztmmqhswvgimmpawgbwzorprefkiolqbclpxvvtqsuyxfprapedncawrvwyxyjludqzdtbykkgzzxelxezmieehvesbaxmpafbanfdfvdmtnoffnxmcefwvgwwdjnuzygxoeddviemzmthatigvqijiauupcjpzeiehyexpfmsvbjkvsakzljrlcvibcqvwcmovhbnthjewzsudiwhqahnayhnnfohqgdndnigbolnudwjjffvivjfmdjtsakricvfnyfcygrtwlwggqwlvrfuqwjgoumbldgqgehvmhxnbyxtoiaaxgxhxhfdqykaevpinuhklghpvgzkabnwiwcwodqwisyrkpyowstigluvebgaiwttwnzkuvmfcpmsuwasmbmvnlposzbupkhzpfgygbozivmejhhyvjxshbuuxbvnlzqwzbhjprkaqeogqxzdnsmkrmvbdlclnevjffzjodgkgisbuovjgsnmuhzfarvjcoxsxqjzcllibqcoihkgpprswugezllabltyivzwwieyfqldjkkbyfppusznvnsiwptritmoyczwnipfbllautpeydblqazgvydxesdgntkrvlrwxnujguqrrfnolugpxwsvyhivhraenemzxyxxcktrmhkepmpovolpbgmxblpysribkximfjmrbrbfufontaangpfjdbqkcvvwafquakdwiqttlqhohsptfyfmgvhzenghofcwzbnyonpzgcsgmssnscmoxveodvaldwcskxdrhpetxzihdoqghvsuxrwylvztmcyunpxcnzurokeffdkpeiznmbortzczkmbjylzajfeqjeacsniqpjyoebergheioyfhfucgpolqsykwdwqnuwgbymyakblhneaeowplgyewjrefkkxgiunkhwrcdoncooaykfxzylfgekejarojoxhrtrzkxpfysuhhezobuvyuxzcjzelliywbuohxgcyegvzucocwiihfqjbuwpulxngaxrrurbcytzwopdyippuyxhjruojenbzcjvvzjpctwkuflohskasumphpaxfkrzwqhheqiiemkvzlbcghypfmjnsshqrthxajdvixxfwvbhbetwxvaeqjduecehfzkofsobchrdqpqaouglovhjpckuclgjnrufdmaqfxookndntemsossbgrdahngewypzlhcwxirhyboeihprbackuiojvbleshhtetyrisexickxtvtxwuyajksnuwqbxuodjzxzsnxpuptqnrufwfljscttnoixvveiutgwyzcyubbugwoipreroyphjotjiefupxsobwsjdfzxurjdodxqspslsuotgltvjjmpvrfxrzsfbsjincvrxqzbaxnblvgvhkdkkjawfdlkfryipruwamtpaqpvplyexlkzqctteexoysmofgpthdyehcqvsvxpipqyiofnopxotekdbyspqroopohkkzqcoikuhvktwrgrqncgvsevlawkzcuudxzihfjnlvjvkuczvddvuiabgpfrmotfebhwtlwigzyikropxnfvtlvmzkzomltvpyoncybbdblyytyycrfpsicgsvzksqgemejeetvaxravacbyspfoylutyryzcewfadqhsnqlwwhzkvhsweyvvjcxfmmceqdecioftgdtuetdllhvxqjgxrhtnwqicuzvebslytyatcqlwldvbdkiyncvhpcaglnykzarxvylgmhabrygigthtuihniyrcaxfcukuocekcglwoukubxchvbwvvcpjbvfungoyazrvzcirlpafbwjyhjizxxlvemozkbwahbndlukmqstsoncwyivojibarktzzxqmepgwrbjjtperuhjyychghelbihbsqnasgnjuschbtpgssfoqwqjjicfdzrysuzlvhdvvqfiaxgohuubjemhxavfucupwmmadihyhtqcdzmdlgabyzgyyjyfxbydaqurffmggfzdfnnqmlmllaousvupvvxjbyxddleyudclwpzwdmbnrnidgrdidszdjgmkggzlissorrwjfddgixeomcvwklenifdhvgegyqfifxzstwioxcgoswuqjtqywwquybujwhiypebngdiraqcueeekdkvlgzzsaemrmerokqcrqfhzjbuvacskujlbyuptandooraxnqzoitortxakjivjndbflestdctbrqsdyruvwzujwsaeldfhhcdbfpqkizwatggvgpikezneqpuryzkdkczjifemhfnccwvrulifqeuosnmhwbkcfaeqbpetlvhgigifjbmpdfivlzatdshwxvbvyybpskrdpqotyipxfsohxlxwruavnbcjlsbaciogqvkjjdowmbcnkfjfltnriwqemxekjbmylvzvnrgxeekdepgkfpoitperbwartimmkfyjxpmpvwgcugtenpacxxzymybrtqtfduplmpktuivwnlxwfrvlqyorhvoavytaqgijhrgbuynfldqtlxnhpfdvlbxzegjkyfplxnxnhwexypdfudtyxjwsudxkzooidthzkuoyqnxjpszyynfzzmuaofusvfqcvxhrbgofeyefwpvplzdzydsyxdaobdkperkxjugpxnzepxkvhaakkydzxaamtdlvcfqqtnmgkqbxekihgigxelmgnkqpssdhjjbimnjboboiyxfsflnuxcpqrxoejuflkfjwicxlzdoxxpemomauofvdhrohocaapnbjwbvlrnscuunxfxhroqhfjcgyaqqnwszvrxqpqdkjkymiygwcnydbukbrbvqdtkpjyeeqkxiswkhkrxcricwhmqsauiztyzieubkgalgduxdyxermeknpiitlnrhocsecfzrgagzsrevawvhtcsuqxccusudzrbbtgwkdwbkbtfklshcapanqsnjggugrhywtouppmeaheuwpriffjmnicbyobgxhgexmksnurkbhgmahheuudqaulkmyeubuiyakpftlbfcnnmframtjghcyeegxbngnwmifflhsjnsgacfmwgtcdzhrrflolqangavivxmjerjfhyznewejvtjvojhvprwtjdroxvjpfzfcrdsvenkvgqdonxwtpqvpmmopdvnatqksfmutmseevwtdrpgsocgiyfzmdtgboaadmfmslbsfcuvhcxwgpqxqvqujrkosfduvxfjzfykonzwqvzvzxkzqigppuhfcabhmmlfdvubqcbxehywjltjyprzusjfpvmpisprlyszhpeyyjzzorxtfxlalefpszblfkqgxvgiubroswiwaaksmbhfohtqswlstrkooxwgimdwymiffoijobsqhxocipnriklewyjofhszrwrkjxxryyyfsdachjreudpjcqdcbhefxmjagzjkthrojpwmgymdvfuvyqkssjsnnwpisqkfmkstmbdjoeoqblyntvvhkiforfhifvgnwdtxtqdmwmjyouykvublnirayriijgxokgwisnvgnucdxjhjhzqxxgriablmloyzbbypzgfgwesvkwjbhbkrhnwxwarchejbixmocevuoidpkqkcwgbdqhmnxkdngllyrkuthaxkpyzpcuqqngipinovmvwpduzzfsmrvhrnamblypfmnrkzclyuggwgwtltmzruyolblwvkbytlbjryukcyknrpofhevilgzkqoxzcysydycqxttegydqxkypovobxvohxowrgnjxhollloxxmvqpidclnrwwpmisswtqzoosgvjkykfskiqmevegieatdhluvrffkhxinqtbmwvrprdjdfkeadrswkxygcvnjycnshbnbzlrohwbgimmqzcflwgzpdcmljttyzswzhjqjrdkzeuuauomgfvbijpxdvinhvwjrydoilzwumsuqtssjvlxojbqldlxsfqgswbuteejiahtrxjlrmefchfdjauockaewgziuvxpxvubqfwpsfalieclziczxthohobdbcehprhtfzcpwridippqekavvbkimmzphaajzcptduwjsqftcgbsqdwlneannbbtosvrafjwrjfsfabmourlzjdvuhpqeznqniybrcnblecnrdpmcimlxmtycvhphrzmltghdbgghqpkqnuedsqxykmbuuhgstcogoydumkaomtvhpknjbsygztkadowvqiptpnwwqhmxmepbfexjammwoeuvvagsbukxzosrvzrsheujrirwzasokqpaktgjrgqspgjnvycywucyalewtncynffzjahkwrcohbthdkxyvwrbazdsjjttwbrwjyphoxtqeqgnjlhypankvvfmeofieemcvgpeqwtjvhjklpgozrcdwjptgdhlsuegnqhmgmbjndcmsaupemiqjhqoojyeqtlytdejqbmktlpfqcvkagozgbeejxalkcfxzfjrzxipbhiwbfnhyokaapigbspxattkazejeiwlletvsnbkphalnrzazfwnppydulfiyaeiuyqppmjsbwjznhjiqnzrhiaifunigjitrjcgcjyqrzleyvnugsuzygdqodaptpzhzoxywsrghkzqpljvktzcbomugpgnocogbaryhahdmsvmrmdpbeqgiobgwuptuppppsbrvrvupxnvfcunlivhhnbxtcbebhukbvyvvmhtcrrdtqlmvlmhhcbeplsibaxhyaempzolhfcsxmccygkwojjnarmzehpixeqfhmngxlgcxrjtbrbwsemmtjmmysvpriawtxjgoaiccdmwcxfberbapwycoplmtjfavmdtwtorvncgwcbdwznwhlsfymnadyrsedpnibafzggvybymyxpcglbbqyrcogjntkwgjxboikuskrkmswigopiqfpuyvlismrzhravhujioylsdtnefsjvpfefkqoiajudnlxknllfphwiqyoaopojnrpagcdtuwlduqtufpuxxvbpzaxlavecohmdqqmhtdilkddjmraclqpbgzaenajssnpvoeowmzmcjmaxlnhuoyrnqqaqvrkswfvexzdlrhrxzplcwfbemlaoagvjxohwwpgmjormlucxaeqfcaqgszgiavokanoomwxxhrzliatfjwxsncjryyepknrkbwqewdkimfmoabppphnppcpamecapslkgjgqsohbmfpeixaugvuaeaqsgaxclgufjsbwehjlarxnblyryzlnbmtproblkuguflgemsitlslxxovxtellpnwqoslkrxrlmosxvxhuhtwskpblbjseipppiprflvdljugbezzjinncliuswdtmrmzqkstlinyxjvkmegwyrcpoujuozsefcscxaxeosugkmvxcupjyvyijdwlswxizzhfsxjinexdztvbslefecbljjhrlutmtrqoivhbpagpcqgjmtbetmwarhxmesmhbeclpbalsbxkgsmjyytuwynkunhugojivvniysfqofccqyaekvcndrkdubrbbpeodqtdqeebiwgzfwtyofmffbuqkgdtivuyfvqauihaspbecowgluhqnfickixbkskiyqejvqptsenrdfbaouqqaangrnlxaskfwlglpobdyafdverlrsdsxycfiiwwjpaljbqujeqjoezilfburkivrexsaqmeyvkprhinmkvqkkxdcfpwvmetgywarjzaxharauhuduecocwmpmgwvrpbbkusyxamrkuigwhaxlrufiolnctvscthrmxthbdivhggeypjsqhkrzzswvvorzgvlibiwvogsoskydhijleeaikmpeaxcytccokanquirbkegytqlmsjlttynmozlehauprkcmxeynzdmsxbxjvhasqwtsieirfauwxpifdciklqcwxiycwmgulqinxhnbzufzjbnmbkwpycjjkuolsfxnrzwvqbvrpaykvddylehrlexkdxqhctknrgghqtsuzimpcpkjzuqgfzaaexhtehmtuzfhvriuyaoyxgyvmibrwseruawlfabwszeukixxfoivkmmncnnejwposwqnycgaytolopuctknniiebxzpgtyyltqpprekbbrmqbflwawimifoqspcxzwnqdxgnpcjarsaqehzhsntvcmquxdjjwzlmixivjnllgmbjkwzxvvmdjasnukmoerjqphmuvatpwoildncsrzgwwcyoxcidxdkoislmuinhjmdowhzdnhdpptlyvpiusreczseilrqiwpbgqtafkwgfnwjnaxnjkisbgagtnksturmdhiwkxaqadwupoawaaigjhefpiexhnqdkijxcpyvkssobcagkjadopuwhbmnscuagwjnjrfoogbhdudrghowdpumnxhlqejlgrteemfhdovmtqpmxpnfthhbmiednkfvegpnwvhojbtdavgwfmkpetdyrrmayiikgagcbeafifxonpeockevwlfpkmqrcqinigqianomjtorcezfzhknpdpmnwvrsocqdkoodpxylrkitpltnkxbwefzxqqonlihcfsduastaicomqsrzlkbszicjncpwzjdoejiasaebxqzizsyxkntlyagpgcoistuejmhbehstbwdehebhdloqwqbyflzqdxryjypewxocllmmagdkugwnoamwmtklmrckvaqpiiljtucjwxfvzdrolwguwhzadiwmtnowhjfmooohgsdsqyfcjkedxrxttfynyysgrmfzvohyxfavxerxapjphogpgeqmpikcuyoysdvzyklbotpeyzvkmuhoouxemupyxdztxeuaaxzvncfxujptvevugewbojskkmlifhieolztmvzugkcznhdcseilwaefjvqqkqgzldzkmdxsykxqvotosayrpfkzjmfysgafycglxzvnxhjrlrtxeodkfnwjyfrizppntjngpypahhuhesgkxktlqybdouzyasngwgzlhfgikedyhitdjxzshfhzlbweevugtrljolczhaxecglqgqlhosgywgosuvrhmwxtunrpirdksmfrbbxlfgoknzaqgyxgciszicygndcncupbwpjvyzfywshppnwhjobcrjfzbyjrczcdalsnrwihkpibyznznullsqpzseotnukhfxpnivzrloyfpdauppzyiihesvmpawrjpszufdomrzygnvmqpjflzpdepmoyznwbuahrulnsftnwvtlucgohbyfmohmddsfuunohdmiwtihqsnmiwyxnfpsuhxiydvyjejjwaxyjjdyfipgtjrlrwbgycwvfrljokekkzuvlevsrrmhugedchgpzalnlycyzpocemrlwgakizxdxhhuwhxbcvqdjbnxlntuzxjoljtynfvdsarmxowothhcjpjwdedrjueiczvhdhvzvjlavxuschkxyidwnzcaucqhnxayohehheveamijgvzmqnubtconujewfnggisqpdcgymgfcwfqcchtvhvtrhpsnzdvwybovbgwunywrsivtbyfacmxjvjxajsplpnfttlnhbyxokskxnftmbaewjijqfmehtcyxnmdeackmjtrydyisytwbegsymsahlbveuyiybaabrgifjmyepdecqqfkykrgitfyvifswmjcezxcdtrczducxdyjiapjggejuxohkyxznmgrzhegyzxifejhcanbqnrhljgwmgtywcnffsvkwtytmyvccshycrjctiuzucfpthxnfdolpulqoprlzryjwvpfbfizmmapevylmjrlfidsghbawryhghumvgznjcqmtijllxvuuxpiofbuhdwyeforrvcyymmtwkfvkfomqybclteoqfifwoiedbxpncseeuasnemhcxtzqvucuveibywaacawxgplxfhrsqiyxaporvnulqmwwvxtrwhibuyhtdlktihzmnfxbcmzecvjdpyokkiizcecdoidmluukzzjrddhtdvwyeisxwsdoxgytgyqgjgjcoxzvzhiszzcpqjznuoguzpbhhbucygoamwunmicwdvjkvydvfmdbqqtbczugehpwcldknjlarkodhuzphnnmrgwrieyuxustkkhizavkvwmbseznguvcvwijciamzksgvghiqstgycaumqjdfzyedoqviaryszppvpnhvqfvkmbrnwvimhxgxdkxoplewqlswlwbjvrxharvdfvrdsasqhqzyxndztlgmftfkkteoiheuahuimihntchzhctezhdprgfpgfvlxxrcemduvaqifizopcbrolrkqkmngqnkjhpbuexfyzfyejsosmsqbpzhshdotksgnrgoahsljcnymhetufasunglvmuzwxepmdsuwoedlwndxsztgeesdvcyjrfryzibqiuntezjegjdiqaeogcqpzxqkmbaycmwyyzaonhxgexuplwfiodlcyoiacldyuohvupvmukksxmhgwliclayoyrkvhjvbsjjdjypdluoakdagphdsfncalpwvmaehsargabrmijhpvknumtjgtqzbpgegxflzgblczzqxnfglxlogvnggeyyjeebpaapvuyaxpwtrlwxytdagituuboemdifgehhgmsjkatwqoskqcjetochkmittwnkqnhahfbuiedpteumshslhtxmkgncgjltbqdijravxzkxxputqruhevuuqpdurguworxhxkqxcqpvfpwpvnzbxmjgxrpajzvdvtgkwoefwdeaotbeapqaqupkvoiykluxrpzgdlvftidvjryglmmkkjcttfqaryvojpgyfeofwigqjzlrnnhcdstmjqhjsojqdgndrdizjidkrpabztvnelspwacrnjfwxhbrqwcxtwiykpfpxdkmbkpioveuvbdmpxnfnrhpwksauprqbxcxdrfcjxruczzsdzprocrfhpkckjzvtodavodklpqwqhkknkrgqwbiqpyjikvmjxsxmwxpvxulovkrzpezdvbkbeqrroxdkzudnphocodenlxraarmgdzymbwavbscjxjynpeucanhefiatkpydsqaxoqsrsfryhrilsyghylpypsbwcuahobwmuqrnxwfscksigmymbajnuhkeksbcbqcfnztzahgepabbywkijqboolekpgfgdbckylcyhwwodxusesbbhkkpbtdslnhkjbfactiuwownbgfezvfhuyrlzenxeigtjoelhcvrzgcppchraxpurzohwwiroreedqnuowrsektacvzaqnjblakqxtwyfomgcskrygusvuxjrtbppwvartyuqoqammlqsldzstbutpkwvochacifhoferdidjgdbtzceltmdafjmzwvkdjwbkubbagtwrwbtlcqzimvnmcafixfwvfhmteaqnovhbcgggdzfodbborphlcwenrrntssgapwkqrbbeqishxrpqzgyapovriwktficsfppvaenbhfgiqxkwsvqsbqseotvbxytzgyfqhhvbyszmakksyzairweznjgkdwctmpwwnoppvqzfahuiyjoebswovbttcnqwjeugniaerjagzvgmtilhgizbtgozcgqgycrddljrvhenlnnqjqpuuplsyxvnyinkxpxujdheoidqvphvcjwgfqubgniauuiysrfnwfuijytgkfzdpbvgdozfnfliskqgnvbbvkmjgcdwqcmykjmnynjycbvsigpwltmamnwdprcuckljvoqwqwjksfofapwehplowndkflsrgnpjpfcloaftxqbsoyflfmoxneseiiaqebncnqinzvcmpgaajifjkaupuwgssgriafyfdzrbagkzmfgpuoaycrabqkzuslhcicpyrukqtqdmlorgvuhwdyobzjhbiqdtijdnjszpohctlrsqclhxqdcuqivkmxztxqehgroqcmrawccmbivgyeidliugietpmsxqxxvczeafmwftevnzzdsowrnracxzlogrwhqaqyycqhrxzprwlzagaaoeitlbkeivpjobgmogbpwhtrirpqikaqypysfhbdjjpteojddfftmabvbwhkrpozxbhbrvglimnmgdqasxkjzvpqkpzmcgflsbsshuvjremmrrtbnfknprxppncgbkybhfcgjsrdpelrqlbnqbumwolcxexjrmrdlggrxxanguhajqoaiwtykjfgtocficbhdhbtznfvlcapbvzdblrpymjuibxkpbwjsuheshpovkfoqyljdievhvcowtuykyuptdzakfcrxbyrkiuhrxxlbeyjcvobqsndptroqancmttbyyvufdwqzpciyxoabutzzhfviblyfausqpoakyhlznfjvjqlrcczubqwdfsavwogvifglkhyfglrrbehghbunqwrpmsaaxiovgxitnzomblnxrbyowrwggggzpizgxoucsxxadlmmrcaqtckjvzhssztiqpsqofsiwyssavscimwjwjcndpirmgdgjvyydvflrolgpqyahbdjyacwqjswlsfjrqtwowbygthdkgmyiurvnhwkhvxxaaidxvwbnfqndglqucmclnnqmtgpykahxcaizbedpyhhjcqkyvdovfrxgpnasncgqstokqnlwcoorsstxkbyprtnbtjxszmbscjlvnqihkzmqkqnripsxposgfedyjykrctynxerlwqalsjfiinvkunsnylmfldylitudkrzqsmkbltutwdpdqxounovmtsyuelvihmvgukxxedbzuepryjsqsbcmtzdgxoysgoaajtebdcslawrptvazfxayazcrxykqlxzaxfxiqegaoremtshgcewcdluvydrhwutcomhdcmdsopiuwvnuygalvosddsmmxezgqozfedlgidiwbkhvkcgesivrgvzmqqiavexdmdrgrffhxxgpiqwkujkjlcolcadshnfxhfnofdnmqnppqaiymadkuepightrfodmauhrsyvuhctzscenlqbvfxggmygvtqtvbhwdaoczloprvfwwmoiuuvbsylfurqobkifaidqqmhitgpynnnhmwyajqbcuabjlw");
    
    
    
    auto res5 =  longestDupSubstring().doit("ababdaebdabedeabbdddbcebaccececbccccebbcaaabaadcadccddaedaacaeddddeceedeaabbbbcbacdaeeebaabdabdbaebadcbdebaaeddcadebedeabbbcbeadbaacdebceebceeccddbeacdcecbcdbceedaeebdaeeabccccbcccbceabedaedaacdbbdbadcdbdddddcdebbcdbcabbebbeabbdccccbaaccbbcecacaebebecdcdcecdeaccccccdbbdebaaaaaaeaaeecdecedcbabedbabdedbaebeedcecebabedbceecacbdecabcebdcbecedccaeaaadbababdccedebeccecaddeabaebbeeccabeddedbeaadbcdceddceccecddbdbeeddabeddadaaaadbeedbeeeaaaeaadaebdacbdcaaabbacacccddbeaacebeeaabaadcabdbaadeaccaecbeaaabccddabbeacdecadebaecccbabeaceccaaeddedcaecddaacebcaecebebebadaceadcaccdeebbcdebcedaeaedacbeecceeebbdbdbaadeeecabdebbaaebdddeeddabcbaaebeabbbcaaeecddecbbbebecdbbbaecceeaabeeedcdecdcaeacabdcbcedcbbcaeeebaabdbaadcebbccbedbabeaddaecdbdbdccceeccaccbdcdadcccceebdabccaebcddaeeecddddacdbdbeebdabecdaeaadbadbebecbcacbbceeabbceecaabdcabebbcdecedbacbcccddcecccecbacddbeddbbbadcbdadbecceebddeacbeeabcdbbaabeabdbbbcaeeadddaeccbcdabceeabaacbeacdcbdceebeaebcceeebdcdcbeaaeeeadabbecdbadbebbecdceaeeecaaaedeceaddedbedbedbddbcbabeadddeccdaadaaeaeeadebbeabcabbdebabeedeeeccadcddaebbedadcdaebabbecedebadbdeacecdcaebcbdababcecaecbcbcdadacaebdedecaadbaaeeebcbeeedaaebbabbeeadadbacdedcbabdaabddccedbeacbecbcccdeaeeabcaeccdaaaddcdecadddabcaedccbdbbccecacbcdecbdcdcbabbeaacddaeeaabccebaaaebacebdcdcbbbdabadeebbdccabcacaacccccbadbdebecdaccabbecdabdbdaebeeadaeecbadedaebcaedeedcaacabaccbbdaccedaedddacbbbdbcaeedbcbecccdbdeddcdadacccdbcdccebdebeaeacecaaadccbbaaddbeebcbadceaebeccecabdadccddbbcbaebeaeadacaebcbbbdbcdaeadbcbdcedebabbaababaacedcbcbceaaabadbdcddadecdcebeeabaadceecaeccdeeabdbabebdcedceaeddaecedcdbccbbedbeecabaecdbba");
    
    return;
}
