pub mod A967_NumbersWithSameConsecutiveDifferences;
pub mod A978_LongestTurbulentSubarray;
pub mod A974_SubarraySumsDivisibleByK;
pub mod A71_SimplifyPath;
pub mod A962_MaximumWidthRamp;
pub mod A114_FlattenBinaryTreetoLinkedList;
pub mod A94_BinaryTreeInorderTraversal;
pub mod A307_RangeSumQueryMutable;
pub mod A264_UglyNumberII;